// src/services/frontPageDataService.ts
import {
  Client,
  DirectorKYC,
  ClientAttachedDoc,
  AdhocRequestItem,
  ComplianceCalendarItem,
  PendingTaxItem,
  PendingTaskItem,
  BillingInvoiceItem,
} from '../types/index.ts';

export const ATTACHED_DOC_TEMPLATES: Array<{ key: string; name: string; categoryNumber: number }> = [
  { key: 'coa', name: 'COA (Certificate of Incorporation / Assessment)', categoryNumber: 1 },
  { key: 'gst_reg', name: 'GST registration', categoryNumber: 2 },
  { key: 'rent_agreement', name: 'Rent agreement', categoryNumber: 3 },
  { key: 'company_pan', name: 'Company PAN', categoryNumber: 4 },
  { key: 'fssai_license', name: 'FSSAI license', categoryNumber: 5 },
  { key: 'trademark', name: 'Trade mark', categoryNumber: 6 },
  { key: 'electricity_bill', name: 'Electricity bill (Latest 2 month)', categoryNumber: 7 },
  { key: 'noc', name: 'NOC', categoryNumber: 8 },
  { key: 'bank_details', name: 'Bank details', categoryNumber: 9 },
  { key: 'moa', name: 'MOA', categoryNumber: 10 },
  { key: 'aoa', name: 'AOA', categoryNumber: 11 },
  { key: 'other_doc', name: 'Other doc (IEC/Drug licences)', categoryNumber: 12 },
  { key: 'epfo', name: 'EPFO', categoryNumber: 13 },
];

export const INITIAL_CLIENTS_DATA: Client[] = [
  {
    id: 'cli_briopox_01',
    businessName: 'Briopox Pvt Ltd',
    contactPerson: 'SN Biswas',
    gstin: '07AABCB9123D1ZX',
    cin: 'U74999DL2021PTC384592',
    address: 'Plot No. 44, Okhla Industrial Area Phase-III, New Delhi - 110020',
    registeredPhone: '+919873875138',
    email: 'accounts@briopox.com',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements', 'debit_credit_notes'],
    expectedBankAccounts: [
      { bankName: 'HDFC Bank Ltd', accountNumber: '50200088991122', ifsc: 'HDFC0000240', accountType: 'Current' },
      { bankName: 'State Bank of India', accountNumber: '389922114400', ifsc: 'SBIN0001234', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_1',
        name: 'SN Biswas',
        din: '08492011',
        phone: '+91 98738 75138',
        email: 'snbiswas@briopox.com',
        aadharNumber: '9842 1284 4821',
        panNumber: 'ABCDB1234F',
        bankDetails: 'HDFC Bank - Cancel Cheque #492810',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
      {
        id: 'dir_2',
        name: 'YX Biswas',
        din: '08492012',
        phone: '+91 98112 34568',
        email: 'yxbiswas@briopox.com',
        aadharNumber: '4910 8291 9043',
        panNumber: 'XYZPB5678K',
        bankDetails: 'SBI - Cancel Cheque #102938',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: false,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'COA_Briopox_2021.pdf', fileSize: '1.2 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'GST_REG_06_Briopox.pdf', fileSize: '850 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_3', docKey: 'rent_agreement', docName: 'Rent agreement', categoryNumber: 3, fileName: 'Okhla_Lease_Deed_2026.pdf', fileSize: '3.4 MB', uploadedAt: '2026-08-20', status: 'verified', expiryDate: '2027-07-31' },
      { id: 'att_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'Briopox_PAN_Card.pdf', fileSize: '420 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_5', docKey: 'fssai_license', docName: 'FSSAI license', categoryNumber: 5, fileName: 'FSSAI_Lic_100200110022.pdf', fileSize: '1.1 MB', uploadedAt: '2026-08-22', status: 'verified' },
      { id: 'att_6', docKey: 'trademark', docName: 'Trade mark', categoryNumber: 6, fileName: 'TM_Class_35_Reg.pdf', fileSize: '980 KB', uploadedAt: '2026-08-25', status: 'verified' },
      { id: 'att_7', docKey: 'electricity_bill', docName: 'Electricity bill (Latest 2 month)', categoryNumber: 7, fileName: 'BSES_Electricity_July_Aug.pdf', fileSize: '650 KB', uploadedAt: '2026-09-02', status: 'verified' },
      { id: 'att_8', docKey: 'noc', docName: 'NOC', categoryNumber: 8, fileName: 'Landlord_NOC_Okhla.pdf', fileSize: '510 KB', uploadedAt: '2026-08-18', status: 'verified' },
      { id: 'att_9', docKey: 'bank_details', docName: 'Bank details', categoryNumber: 9, fileName: 'HDFC_Bank_Mandate.pdf', fileSize: '730 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_10', docKey: 'moa', docName: 'MOA', categoryNumber: 10, fileName: 'MOA_Briopox_Pvt_Ltd.pdf', fileSize: '2.8 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_11', docKey: 'aoa', docName: 'AOA', categoryNumber: 11, fileName: 'AOA_Briopox_Pvt_Ltd.pdf', fileSize: '2.4 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_12', docKey: 'other_doc', docName: 'Other doc (IEC/Drug licences)', categoryNumber: 12, fileName: 'IEC_Briopox_ImportExport.pdf', fileSize: '910 KB', uploadedAt: '2026-08-28', status: 'verified' },
      { id: 'att_13', docKey: 'epfo', docName: 'EPFO', categoryNumber: 13, fileName: 'EPFO_Registration_DL_890.pdf', fileSize: '620 KB', uploadedAt: '2026-09-01', status: 'verified' },
    ],
  },
  {
    id: 'cli_apex_01',
    businessName: 'Apex Engineering Works',
    contactPerson: 'Suresh Mehta',
    gstin: '27AAACA1234A1Z5',
    cin: 'U28110MH2018PTC305891',
    address: 'Plot 12-B, MIDC Industrial Area, Andheri East, Mumbai - 400093',
    registeredPhone: '+919820112345',
    email: 'accounts@apexengineering.in',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements', 'debit_credit_notes'],
    expectedBankAccounts: [
      { bankName: 'HDFC Bank', accountNumber: '50200012345678', ifsc: 'HDFC0000123', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_apex_1',
        name: 'Suresh Mehta',
        din: '07123901',
        phone: '+91 98201 12345',
        email: 'suresh@apexengineering.in',
        aadharNumber: '8910 2341 5567',
        panNumber: 'AAAPM1234K',
        bankDetails: 'HDFC Cancel Cheque #891230',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_apex_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'Apex_COA.pdf', fileSize: '1.4 MB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'GST_Apex.pdf', fileSize: '900 KB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'PAN_Apex.pdf', fileSize: '410 KB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_10', docKey: 'moa', docName: 'MOA', categoryNumber: 10, fileName: 'Apex_MOA.pdf', fileSize: '2.1 MB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_11', docKey: 'aoa', docName: 'AOA', categoryNumber: 11, fileName: 'Apex_AOA.pdf', fileSize: '1.9 MB', uploadedAt: '2026-08-10', status: 'verified' },
    ],
  },
  {
    id: 'cli_bluebell_02',
    businessName: 'Bluebell Textiles Pvt Ltd',
    contactPerson: 'Anita Desai',
    gstin: '24AABCB5678B1Z2',
    cin: 'U17120GJ2019PTC109482',
    address: 'Surat Textile Market, Ring Road, Surat, Gujarat - 395002',
    registeredPhone: '+919825067890',
    email: 'finance@bluebelltextiles.com',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
    expectedBankAccounts: [
      { bankName: 'ICICI Bank Ltd', accountNumber: '001205009876', ifsc: 'ICIC0000012', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_blue_1',
        name: 'Anita Desai',
        din: '06819203',
        phone: '+91 98250 67890',
        email: 'anita@bluebelltextiles.com',
        aadharNumber: '6712 9012 3412',
        panNumber: 'AADPD4512E',
        bankDetails: 'ICICI Cancel Cheque #349102',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_bb_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'Bluebell_COA.pdf', fileSize: '1.1 MB', uploadedAt: '2026-08-12', status: 'verified' },
      { id: 'att_bb_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'Bluebell_GST.pdf', fileSize: '780 KB', uploadedAt: '2026-08-12', status: 'verified' },
      { id: 'att_bb_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'Bluebell_PAN.pdf', fileSize: '390 KB', uploadedAt: '2026-08-12', status: 'verified' },
    ],
  },
];

export const INITIAL_COMPLIANCE_CALENDAR: ComplianceCalendarItem[] = [
  {
    id: 'cal_1',
    dueDate: '2026-10-05',
    displayDate: '5 Oct',
    eventTitle: 'GSTR-1 filing',
    category: 'GST',
    applicableTo: 'Monthly Taxpayers with Turnover > ₹5 Cr or opting for monthly filing',
    status: 'Upcoming',
    description: 'Statement of outward supplies of goods or services for the previous calendar month.',
    penaltyInfo: 'Late fee ₹50/day (₹20/day for Nil return)',
    isAutoGenerated: true,
    affectedClientsCount: 4,
  },
  {
    id: 'cal_2',
    dueDate: '2026-10-07',
    displayDate: '7 Oct',
    eventTitle: 'TDS deposit',
    category: 'TDS',
    applicableTo: 'All Deductors / Entities deducting Tax at Source for previous month',
    status: 'Upcoming',
    description: 'Statutory challan deposit (ITNS 281) for tax deducted at source under Section 192, 194C, 194J, etc.',
    penaltyInfo: 'Interest @ 1.5% per month from date of deduction',
    isAutoGenerated: true,
    affectedClientsCount: 5,
  },
  {
    id: 'cal_3',
    dueDate: '2026-10-10',
    displayDate: '10 Oct',
    eventTitle: 'GSTR-7 filing',
    category: 'GST',
    applicableTo: 'Government departments & designated entities deducting GST TDS',
    status: 'Upcoming',
    description: 'Monthly return for authorities deducting tax at source under GST.',
    penaltyInfo: 'Late fee ₹50/day',
    isAutoGenerated: true,
    affectedClientsCount: 1,
  },
  {
    id: 'cal_4',
    dueDate: '2026-10-11',
    displayDate: '11 Oct',
    eventTitle: 'GSTR-1 filing for QRMP clients',
    category: 'GST',
    applicableTo: 'Quarterly Return Monthly Payment (QRMP) Scheme Taxpayers (IFF / Q2)',
    status: 'Upcoming',
    description: 'Invoice Furnishing Facility (IFF) / Quarterly GSTR-1 for QRMP registered businesses.',
    penaltyInfo: 'Invoices cannot be reflected to buyers if delayed',
    isAutoGenerated: true,
    affectedClientsCount: 2,
  },
  {
    id: 'cal_5',
    dueDate: '2026-10-13',
    displayDate: '13 Oct',
    eventTitle: 'GSTR-6 filing',
    category: 'GST',
    applicableTo: 'Input Service Distributors (ISD)',
    status: 'Upcoming',
    description: 'Monthly return for Input Service Distributor distributing ITC to branch units.',
    penaltyInfo: 'Late fee ₹50/day',
    isAutoGenerated: true,
    affectedClientsCount: 1,
  },
  {
    id: 'cal_6',
    dueDate: '2026-10-15',
    displayDate: '15 Oct',
    eventTitle: 'Advance tax payment, Q2',
    category: 'Income Tax',
    applicableTo: 'Corporate and Non-Corporate Taxpayers with estimated tax liability ≥ ₹10,000',
    status: 'Urgent',
    description: 'Second installment of advance tax (45% of cumulative liability) for AY 2027-28.',
    penaltyInfo: 'Interest under Section 234C @ 1% per month',
    isAutoGenerated: true,
    affectedClientsCount: 6,
  },
  {
    id: 'cal_7',
    dueDate: '2026-10-20',
    displayDate: '20 Oct',
    eventTitle: 'GSTR-3B filing',
    category: 'GST',
    applicableTo: 'Regular Monthly Taxpayers',
    status: 'Upcoming',
    description: 'Summary return & statutory tax payment for outward supplies and input tax credit.',
    penaltyInfo: 'Late fee ₹50/day + 18% p.a. interest on unpaid net tax',
    isAutoGenerated: true,
    affectedClientsCount: 5,
  },
  {
    id: 'cal_8',
    dueDate: '2026-10-22',
    displayDate: '22 Oct',
    eventTitle: 'GSTR-3B filing for QRMP clients (Group 1)',
    category: 'GST',
    applicableTo: 'QRMP Scheme clients in Group 1 states (Maharashtra, Gujarat, Karnataka, etc.)',
    status: 'Upcoming',
    description: 'Quarterly summary return for taxpayers in Southern and Western states.',
    penaltyInfo: 'Late fee ₹50/day',
    isAutoGenerated: true,
    affectedClientsCount: 2,
  },
  {
    id: 'cal_9',
    dueDate: '2026-10-24',
    displayDate: '24 Oct',
    eventTitle: 'GSTR-3B filing for QRMP clients (Group 2)',
    category: 'GST',
    applicableTo: 'QRMP Scheme clients in Group 2 states (Delhi, UP, Bengal, Punjab, etc.)',
    status: 'Upcoming',
    description: 'Quarterly summary return for taxpayers in Northern and Eastern states.',
    penaltyInfo: 'Late fee ₹50/day',
    isAutoGenerated: true,
    affectedClientsCount: 2,
  },
  {
    id: 'cal_10',
    dueDate: '2026-10-30',
    displayDate: '30 Oct',
    eventTitle: 'TDS return filing for Q2',
    category: 'TDS',
    applicableTo: 'All Deductors submitting Quarterly Form 24Q, 26Q, 27Q for Q2 (July - Sept)',
    status: 'Upcoming',
    description: 'Quarterly statement of TDS deduction & challan mapping to deductee PANs.',
    penaltyInfo: 'Fee under Section 234E @ ₹200/day + Section 271H penalty',
    isAutoGenerated: true,
    affectedClientsCount: 5,
  },
  {
    id: 'cal_11',
    dueDate: '2026-10-31',
    displayDate: '31 Oct',
    eventTitle: 'Tax audit report filing',
    category: 'Audit',
    applicableTo: 'Corporate Assessees and Non-Corporate Assessees subject to statutory Tax Audit u/s 44AB',
    status: 'Urgent',
    description: 'Submission of Form 3CA/3CB and Form 3CD by Chartered Accountant for FY 2025-26 (AY 2026-27).',
    penaltyInfo: 'Penalty u/s 271B: 0.5% of turnover or ₹1,50,000 (whichever is less)',
    isAutoGenerated: true,
    affectedClientsCount: 3,
  },
];

export const INITIAL_ADHOC_REQUESTS: AdhocRequestItem[] = [
  {
    id: 'adhoc_1',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'GST Amendment etc',
    title: 'Addition of Additional Place of Business in GST Portal',
    description: 'Update warehouse address in Noida Sector 63 on GST portal with rent agreement and NOC.',
    status: 'In Progress',
    priority: 'High',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 4500,
    targetDeadline: '2026-10-08',
    createdAt: '2026-09-28',
    notes: 'Rent agreement verified, awaiting client OTP on registered Aadhaar.',
  },
  {
    id: 'adhoc_2',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'ROC work (Director KYC, Name change, objective amendment, etc)',
    title: 'Annual ROC Director KYC (DIR-3 KYC) for SN Biswas & YX Biswas',
    description: 'Filing of Web-based DIR-3 KYC for both active directors before MCA cutoff.',
    status: 'Review',
    priority: 'Medium',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 3000,
    targetDeadline: '2026-10-10',
    createdAt: '2026-09-25',
    notes: 'Forms prepared, pending CA digital signature verification.',
  },
  {
    id: 'adhoc_3',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    serviceCategory: 'Projected Report',
    title: 'Projected CMA Report & 3-Year Balance Sheet for Working Capital Loan',
    description: 'Bank credit facility expansion report requested by HDFC Bank for ₹2.5 Cr OD limit.',
    status: 'In Progress',
    priority: 'High',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 18000,
    targetDeadline: '2026-10-14',
    createdAt: '2026-09-22',
    notes: 'Draft financial model completed, ratio analysis under review with CA Suraj Dutta.',
  },
  {
    id: 'adhoc_4',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    serviceCategory: 'Trademark',
    title: 'Trademark Class 24 & Class 25 Examination Report Response',
    description: 'Legal reply to examination report raised by Trade Marks Registry Mumbai for logo brand.',
    status: 'Pending',
    priority: 'Medium',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 8500,
    targetDeadline: '2026-10-18',
    createdAt: '2026-09-29',
    notes: 'Prior user affidavit draft being prepared.',
  },
  {
    id: 'adhoc_5',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'PnL and Balancesheet',
    title: 'Provisional PnL & Balance Sheet as of 30th September 2026',
    description: 'Quarterly management accounts for investor board review.',
    status: 'Completed',
    priority: 'Low',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 7500,
    targetDeadline: '2026-09-30',
    completedDate: '2026-09-29',
    createdAt: '2026-09-20',
    notes: 'Signed copies delivered to director SN Biswas.',
  },
];

export const INITIAL_PENDING_TAX_7_DAYS: PendingTaxItem[] = [
  {
    id: 'pt_1',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taxType: 'GSTR-1',
    dueDate: '2026-10-05',
    daysRemaining: 5,
    estimatedTaxAmount: 142500,
    status: 'Ready for Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-29',
  },
  {
    id: 'pt_2',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taxType: 'GSTR-1',
    dueDate: '2026-10-05',
    daysRemaining: 5,
    estimatedTaxAmount: 285000,
    status: 'Under Computation',
    registeredPhone: '+919820112345',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-28',
  },
  {
    id: 'pt_3',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taxType: 'TDS Deposit',
    dueDate: '2026-10-07',
    daysRemaining: 7,
    estimatedTaxAmount: 64200,
    status: 'Ready for Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-30',
  },
  {
    id: 'pt_4',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    taxType: 'TDS Deposit',
    dueDate: '2026-10-07',
    daysRemaining: 7,
    estimatedTaxAmount: 48900,
    status: 'Pending Files',
    registeredPhone: '+919825067890',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-27',
  },
];

export const INITIAL_BILLING_INVOICES: BillingInvoiceItem[] = [
  {
    id: 'inv_101',
    invoiceNumber: 'PS/2026-27/0412',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceDescription: 'Monthly GST Compliance & GSTR-3B Retainer (August 2026)',
    serviceCategory: 'Routine GST Filing',
    period: 'August 2026',
    professionalFee: 5000,
    gstAmount: 900,
    totalPayable: 5900,
    invoiceDate: '2026-09-05',
    dueDate: '2026-09-20',
    status: 'Paid',
    paymentMode: 'NEFT / IMPS',
    receiptNumber: 'REC-2026-0391',
  },
  {
    id: 'inv_102',
    invoiceNumber: 'PS/2026-27/0458',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceDescription: 'Provisional PnL and Balance Sheet Preparation & Investor Report',
    serviceCategory: 'Adhoc Service',
    period: 'Q2 FY 2026-27',
    professionalFee: 7500,
    gstAmount: 1350,
    totalPayable: 8850,
    invoiceDate: '2026-09-29',
    dueDate: '2026-10-15',
    status: 'Pending',
  },
  {
    id: 'inv_103',
    invoiceNumber: 'PS/2026-27/0440',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    serviceDescription: 'Statutory Tax Audit u/s 44AB & Form 3CD Compilation',
    serviceCategory: 'Tax Audit',
    period: 'FY 2025-26',
    professionalFee: 35000,
    gstAmount: 6300,
    totalPayable: 41300,
    invoiceDate: '2026-09-15',
    dueDate: '2026-10-05',
    status: 'Pending',
  },
  {
    id: 'inv_104',
    invoiceNumber: 'PS/2026-27/0389',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    serviceDescription: 'Trademark Examination Response Filing Class 24 & 25',
    serviceCategory: 'Adhoc Service',
    period: 'One-Time',
    professionalFee: 8500,
    gstAmount: 1530,
    totalPayable: 10030,
    invoiceDate: '2026-09-28',
    dueDate: '2026-10-12',
    status: 'Pending',
  },
];

export const INITIAL_ACCUMULATED_TASKS_7_DAYS: PendingTaskItem[] = [
  // 1. Statutory Tax Filings
  {
    id: 'task_tax_1',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Filing',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'GSTR-1 Monthly Return Filing (September 2026)',
    taskDescription: 'Finalize and file GSTR-1 outward supplies return on GST portal before statutory cutoff.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'critical',
    estimatedAmount: 142500,
    amountLabel: 'Est. Output Tax',
    status: 'Ready for Filing',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-29',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_2',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Deposit',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'TDS Challan Deposit u/s 194C/194J (September 2026)',
    taskDescription: 'Generate ITNS 281 Challan and ensure client bank payment for TDS deduction on contractor and professional bills.',
    dueDate: '2026-10-07',
    daysRemaining: 5,
    urgency: 'urgent',
    estimatedAmount: 64200,
    amountLabel: 'TDS Payable',
    status: 'Challan Ready',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-30',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_3',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Filing',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taskTitle: 'GSTR-1 Monthly Return Filing (September 2026)',
    taskDescription: 'Review auto-extracted sales register and submit GSTR-1 to prevent e-way bill generation blocking.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'critical',
    estimatedAmount: 285000,
    amountLabel: 'Est. Taxable Base',
    status: 'Under Computation',
    registeredPhone: '+919820112345',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-28',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_4',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Deposit',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    taskTitle: 'TDS Deposit for September 2026 Deductions',
    taskDescription: 'TDS challan payment required on income-tax portal. Missing salary sheet deduction breakdown.',
    dueDate: '2026-10-07',
    daysRemaining: 5,
    urgency: 'urgent',
    estimatedAmount: 48900,
    amountLabel: 'Est. TDS Due',
    status: 'Pending Files',
    registeredPhone: '+919825067890',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-27',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },

  // 2. GST Document Intake & Upload Queue
  {
    id: 'task_intake_1',
    sourceSection: 'gst_intake',
    sourceSectionName: 'GST Document Intake',
    clientId: 'cli_delta_03',
    clientName: 'Delta Logistics Corp',
    clientGstin: '06AABCD9012C1Z4',
    taskTitle: 'September 2026 GST Invoices & Bank Statements Missing',
    taskDescription: 'Client has not uploaded purchase register and bank statements via portal. 2 reminders already sent.',
    dueDate: '2026-10-04',
    daysRemaining: 2,
    urgency: 'critical',
    status: 'Awaiting Client Uploads',
    registeredPhone: '+919811009988',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-30',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },

  // 3. Client Workbook Approvals Queue
  {
    id: 'task_approval_1',
    sourceSection: 'client_approval',
    sourceSectionName: 'Client Review & Sign-Off',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'August 2026 Reconciled GST Workbook Sign-Off Pending',
    taskDescription: 'Reconciliation completed. Client has not confirmed the draft GSTR-3B tax liability summary in client portal.',
    dueDate: '2026-10-06',
    daysRemaining: 4,
    urgency: 'urgent',
    status: 'Awaiting Client Confirmation',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-28',
    actionType: 'open_portal',
    targetTab: 'client-portal',
  },

  // 4. Billing & Fee Collections
  {
    id: 'task_billing_1',
    sourceSection: 'billing',
    sourceSectionName: 'Billing & Fee Collection',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taskTitle: 'Invoice #PS/2026-27/0440 - Tax Audit Retainer Due',
    taskDescription: 'Professional fee for Statutory Tax Audit FY 2025-26 compilation pending payment.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'urgent',
    estimatedAmount: 41300,
    amountLabel: 'Fee Payable',
    status: 'Pending Payment',
    registeredPhone: '+919820112345',
    assignedStaff: 'CA Shekhar Das',
    lastReminderSent: '2026-09-29',
    actionType: 'whatsapp_client',
    targetTab: 'billing-finance',
  },
  {
    id: 'task_billing_2',
    sourceSection: 'billing',
    sourceSectionName: 'Billing & Fee Collection',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'Invoice #PS/2026-27/0412 - Routine GST Filing Retainer',
    taskDescription: 'Monthly GST Retainer invoice for August 2026 pending clearance.',
    dueDate: '2026-10-08',
    daysRemaining: 6,
    urgency: 'upcoming',
    estimatedAmount: 5900,
    amountLabel: 'Fee Payable',
    status: 'Pending Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'CA Shekhar Das',
    lastReminderSent: '2026-09-25',
    actionType: 'whatsapp_client',
    targetTab: 'billing-finance',
  },

  // 5. Adhoc Client Inquiries / Tickets
  {
    id: 'task_adhoc_1',
    sourceSection: 'adhoc',
    sourceSectionName: 'Adhoc Client Request',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'GST Additional Place of Business Amendment (Sector 63 Warehouse)',
    taskDescription: 'Rent deed verified. Awaiting client Aadhaar OTP verification to submit amendment on GST portal.',
    dueDate: '2026-10-08',
    daysRemaining: 6,
    urgency: 'urgent',
    estimatedAmount: 4500,
    amountLabel: 'Fee Quote',
    status: 'In Progress (Awaiting OTP)',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    actionType: 'view_section',
    targetTab: 'adhoc-requests',
  },
];
