// src/services/frontPageDataService.ts
import {
  Client,
  DirectorKYC,
  ClientAttachedDoc,
  AdhocRequestItem,
  ComplianceCalendarItem,
  PendingTaxItem,
  PendingTaskItem,
  BillingInvoiceItem,
} from '../types/index.ts';
import { generateStatutoryCalendar, REGULATORY_PORTALS } from './statutoryComplianceService.ts';

export { REGULATORY_PORTALS };

export const ATTACHED_DOC_TEMPLATES: Array<{ key: string; name: string; categoryNumber: number }> = [
  { key: 'coa', name: 'COA (Certificate of Incorporation / Assessment)', categoryNumber: 1 },
  { key: 'gst_reg', name: 'GST registration', categoryNumber: 2 },
  { key: 'rent_agreement', name: 'Rent agreement', categoryNumber: 3 },
  { key: 'company_pan', name: 'Company PAN', categoryNumber: 4 },
  { key: 'fssai_license', name: 'FSSAI license', categoryNumber: 5 },
  { key: 'trademark', name: 'Trade mark', categoryNumber: 6 },
  { key: 'electricity_bill', name: 'Electricity bill (Latest 2 month)', categoryNumber: 7 },
  { key: 'noc', name: 'NOC', categoryNumber: 8 },
  { key: 'bank_details', name: 'Bank details', categoryNumber: 9 },
  { key: 'moa', name: 'MOA', categoryNumber: 10 },
  { key: 'aoa', name: 'AOA', categoryNumber: 11 },
  { key: 'other_doc', name: 'Other doc (IEC/Drug licences)', categoryNumber: 12 },
  { key: 'epfo', name: 'EPFO', categoryNumber: 13 },
];

export const INITIAL_CLIENTS_DATA: Client[] = [
  {
    id: 'cli_zylker_01',
    displayName: 'Zylker',
    businessName: 'Zylker Agriculture',
    contactPerson: 'Mr. Suresh',
    gstin: '27AABCS1234D1Z9',
    cin: 'U01100MH2020PTC345678',
    address: 'Suite 401, Grand Financial Plaza, New York, U.S.A.',
    city: 'New York',
    state: 'NY',
    country: 'U.S.A.',
    pincode: '10001',
    registeredPhone: '+1 9999999999',
    email: 'zylker.agriculture@zylker.com',
    assignedStaffId: 'staff_dwaipayan_01',
    assignedStaffName: 'Dwaipayan Bose',
    active: true,
    associatedApps: ['Books', 'Expense', 'Inventory'],
    unbilledTasksCount: 0,
    totalHoursLogged: 0,
    onboardingProgressPercent: 33,
    pendingTasksCount: 7,
    openClientRequestsCount: 4,
    managedBy: [
      { id: 'usr_dwaipayan', name: 'Dwaipayan Bose', role: 'Managing Partner' },
    ],
    contactPersons: [
      {
        id: 'cp_1',
        name: 'Mr. Suresh',
        email: 'zylker.agriculture@zylker.com',
        countryCode: '+1',
        phone: '9999999999',
        phoneType: 'Mobile',
        isPrimary: true,
        designation: 'Managing Director',
        department: 'Executive',
      },
      {
        id: 'cp_2',
        name: 'Mr. Charles Stone',
        email: 'charles.stone@zylker.com',
        countryCode: '+1',
        phone: '9888888888',
        phoneType: 'Mobile',
        isPrimary: false,
        designation: 'Chief Financial Officer',
        department: 'Finance',
      },
    ],
    notes: [
      {
        id: 'note_1',
        text: 'Client requested September 2026 purchase ledger cross-check with GSTR-2B before return finalization.',
        isBold: true,
        authorName: 'Dwaipayan Bose',
        createdAt: 'Yesterday, 04:30 PM',
      },
    ],
    clientRequests: [
      {
        id: 'cr_1',
        requestNumber: 1,
        title: 'Books Request',
        assignedTo: 'Dwaipayan Bose',
        status: 'Open',
        priority: 'Very Low',
        clientName: 'Zylker Agriculture',
        associatedApp: 'Books',
        createdAt: '2026-10-01',
      },
      {
        id: 'cr_2',
        requestNumber: 2,
        title: 'Q2 Corporate Card Expense Receipts',
        assignedTo: 'Dwaipayan Bose',
        status: 'Open',
        priority: 'Medium',
        clientName: 'Zylker Agriculture',
        associatedApp: 'Expense',
        createdAt: '2026-10-03',
      },
    ],
    insightsData: {
      agedReceivablesOver45Days: 0,
      agedPayablesOver45Days: 0,
      cashFlowTrend: 'Stable',
      averageDebtorAgeDays: 28,
      generalLedgerIssues: 1,
      relativeSizeFactor: 1.4,
      topExpenses: [
        { category: 'Freight & Logistics', amount: 45000 },
        { category: 'Warehouse Lease', amount: 65000 },
      ],
    },
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
    expectedBankAccounts: [
      { bankName: 'Chase Bank NA', accountNumber: '402910293847', ifsc: 'CHAS0001', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [],
    attachedDocuments: [],
  },
  {
    id: 'cli_standard_01',
    displayName: 'Standard',
    businessName: 'Standard',
    contactPerson: 'Harish Chandra',
    gstin: '07AAACS1234D1Z1',
    address: 'Nariman Point, Mumbai - 400021',
    registeredPhone: '+91 98200 11223',
    email: 'contact@standard.com',
    assignedStaffName: 'Pooja Verma',
    active: true,
    associatedApps: ['Books'],
    unbilledTasksCount: 0,
    totalHoursLogged: 0,
    onboardingProgressPercent: 50,
    pendingTasksCount: 0,
    openClientRequestsCount: 0,
    managedBy: [{ id: 'usr_pooja', name: 'Pooja Verma', role: 'Senior Associate' }],
    contactPersons: [
      {
        id: 'cp_std_1',
        name: 'Harish Chandra',
        email: 'contact@standard.com',
        countryCode: '+91',
        phone: '9820011223',
        phoneType: 'Work',
        isPrimary: true,
        designation: 'Proprietor',
        department: 'Operations',
      },
    ],
    notes: [],
    clientRequests: [],
    insightsData: {
      agedReceivablesOver45Days: 12000,
      agedPayablesOver45Days: 0,
      cashFlowTrend: 'Positive',
      averageDebtorAgeDays: 19,
      generalLedgerIssues: 0,
      relativeSizeFactor: 1.0,
      topExpenses: [],
    },
    requiredChecklist: ['sales_invoices'],
    expectedBankAccounts: [],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
  },
  {
    id: 'cli_social_corn_01',
    displayName: 'Social Corn',
    businessName: 'Social Corn',
    contactPerson: 'Rajesh Kumar',
    gstin: '07DWAPK0131H1Z1',
    cin: 'U74999DL2021PTC384592',
    address: 'Plot No. 44, Okhla Industrial Area Phase III, New Delhi 110020',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    pincode: '110020',
    registeredPhone: '+919811234567',
    email: 'director@socialcorn.com',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    associatedApps: ['Books', 'Expense', 'Inventory'],
    unbilledTasksCount: 2,
    totalHoursLogged: 14.5,
    onboardingProgressPercent: 100,
    pendingTasksCount: 3,
    openClientRequestsCount: 2,
    managedBy: [
      { id: 'usr_suraj', name: 'CA Suraj Dutta', role: 'Partner' },
      { id: 'usr_pooja', name: 'Pooja Verma', role: 'Senior Associate' },
    ],
    contactPersons: [
      {
        id: 'cp_brio_1',
        name: 'SN Biswas',
        email: 'accounts@briopox.com',
        countryCode: '+91',
        phone: '9873875138',
        phoneType: 'Mobile',
        isPrimary: true,
        designation: 'Director',
        department: 'Finance',
      },
    ],
    notes: [
      {
        id: 'note_brio_1',
        text: 'Statutory audit documentation completed for FY 25-26. 10-Sheet workpapers verified.',
        isBold: false,
        authorName: 'CA Suraj Dutta',
        createdAt: '3 days ago',
      },
    ],
    clientRequests: [
      {
        id: 'cr_brio_1',
        requestNumber: 101,
        title: 'GST Input Tax Credit Ineligible Invoices List',
        assignedTo: 'Pooja Verma',
        status: 'Needs Review',
        priority: 'High',
        clientName: 'Social Corn',
        associatedApp: 'GST',
        createdAt: '2026-10-02',
      },
    ],
    insightsData: {
      agedReceivablesOver45Days: 45000,
      agedPayablesOver45Days: 18000,
      cashFlowTrend: 'Strong',
      averageDebtorAgeDays: 32,
      generalLedgerIssues: 0,
      relativeSizeFactor: 1.2,
      topExpenses: [
        { category: 'Software Subscriptions', amount: 120000 },
        { category: 'Office Lease', amount: 85000 },
      ],
    },
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements', 'debit_credit_notes'],
    expectedBankAccounts: [
      { bankName: 'HDFC Bank Ltd', accountNumber: '50200088991122', ifsc: 'HDFC0000240', accountType: 'Current' },
      { bankName: 'State Bank of India', accountNumber: '389922114400', ifsc: 'SBIN0001234', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_1',
        name: 'SN Biswas',
        din: '08492011',
        phone: '+91 98738 75138',
        email: 'snbiswas@briopox.com',
        aadharNumber: '9842 1284 4821',
        panNumber: 'ABCDB1234F',
        bankDetails: 'HDFC Bank - Cancel Cheque #492810',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
      {
        id: 'dir_2',
        name: 'YX Biswas',
        din: '08492012',
        phone: '+91 98112 34568',
        email: 'yxbiswas@briopox.com',
        aadharNumber: '4910 8291 9043',
        panNumber: 'XYZPB5678K',
        bankDetails: 'SBI - Cancel Cheque #102938',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: false,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'COA_Briopox_2021.pdf', fileSize: '1.2 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'GST_REG_06_Briopox.pdf', fileSize: '850 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_3', docKey: 'rent_agreement', docName: 'Rent agreement', categoryNumber: 3, fileName: 'Okhla_Lease_Deed_2026.pdf', fileSize: '3.4 MB', uploadedAt: '2026-08-20', status: 'verified', expiryDate: '2027-07-31' },
      { id: 'att_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'Briopox_PAN_Card.pdf', fileSize: '420 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_5', docKey: 'fssai_license', docName: 'FSSAI license', categoryNumber: 5, fileName: 'FSSAI_Lic_100200110022.pdf', fileSize: '1.1 MB', uploadedAt: '2026-08-22', status: 'verified' },
      { id: 'att_6', docKey: 'trademark', docName: 'Trade mark', categoryNumber: 6, fileName: 'TM_Class_35_Reg.pdf', fileSize: '980 KB', uploadedAt: '2026-08-25', status: 'verified' },
      { id: 'att_7', docKey: 'electricity_bill', docName: 'Electricity bill (Latest 2 month)', categoryNumber: 7, fileName: 'BSES_Electricity_July_Aug.pdf', fileSize: '650 KB', uploadedAt: '2026-09-02', status: 'verified' },
      { id: 'att_8', docKey: 'noc', docName: 'NOC', categoryNumber: 8, fileName: 'Landlord_NOC_Okhla.pdf', fileSize: '510 KB', uploadedAt: '2026-08-18', status: 'verified' },
      { id: 'att_9', docKey: 'bank_details', docName: 'Bank details', categoryNumber: 9, fileName: 'HDFC_Bank_Mandate.pdf', fileSize: '730 KB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_10', docKey: 'moa', docName: 'MOA', categoryNumber: 10, fileName: 'MOA_Briopox_Pvt_Ltd.pdf', fileSize: '2.8 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_11', docKey: 'aoa', docName: 'AOA', categoryNumber: 11, fileName: 'AOA_Briopox_Pvt_Ltd.pdf', fileSize: '2.4 MB', uploadedAt: '2026-08-15', status: 'verified' },
      { id: 'att_12', docKey: 'other_doc', docName: 'Other doc (IEC/Drug licences)', categoryNumber: 12, fileName: 'IEC_Briopox_ImportExport.pdf', fileSize: '910 KB', uploadedAt: '2026-08-28', status: 'verified' },
      { id: 'att_13', docKey: 'epfo', docName: 'EPFO', categoryNumber: 13, fileName: 'EPFO_Registration_DL_890.pdf', fileSize: '620 KB', uploadedAt: '2026-09-01', status: 'verified' },
    ],
  },
  {
    id: 'cli_apex_01',
    businessName: 'Apex Engineering Works',
    contactPerson: 'Suresh Mehta',
    gstin: '27AAACA1234A1Z5',
    cin: 'U28110MH2018PTC305891',
    address: 'Plot 12-B, MIDC Industrial Area, Andheri East, Mumbai - 400093',
    registeredPhone: '+919820112345',
    email: 'accounts@apexengineering.in',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements', 'debit_credit_notes'],
    expectedBankAccounts: [
      { bankName: 'HDFC Bank', accountNumber: '50200012345678', ifsc: 'HDFC0000123', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_apex_1',
        name: 'Suresh Mehta',
        din: '07123901',
        phone: '+91 98201 12345',
        email: 'suresh@apexengineering.in',
        aadharNumber: '8910 2341 5567',
        panNumber: 'AAAPM1234K',
        bankDetails: 'HDFC Cancel Cheque #891230',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_apex_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'Apex_COA.pdf', fileSize: '1.4 MB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'GST_Apex.pdf', fileSize: '900 KB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'PAN_Apex.pdf', fileSize: '410 KB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_10', docKey: 'moa', docName: 'MOA', categoryNumber: 10, fileName: 'Apex_MOA.pdf', fileSize: '2.1 MB', uploadedAt: '2026-08-10', status: 'verified' },
      { id: 'att_apex_11', docKey: 'aoa', docName: 'AOA', categoryNumber: 11, fileName: 'Apex_AOA.pdf', fileSize: '1.9 MB', uploadedAt: '2026-08-10', status: 'verified' },
    ],
  },
  {
    id: 'cli_bluebell_02',
    businessName: 'Bluebell Textiles Pvt Ltd',
    contactPerson: 'Anita Desai',
    gstin: '24AABCB5678B1Z2',
    cin: 'U17120GJ2019PTC109482',
    address: 'Surat Textile Market, Ring Road, Surat, Gujarat - 395002',
    registeredPhone: '+919825067890',
    email: 'finance@bluebelltextiles.com',
    assignedStaffId: 'staff_pooja_02',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    active: true,
    requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
    expectedBankAccounts: [
      { bankName: 'ICICI Bank Ltd', accountNumber: '001205009876', ifsc: 'ICIC0000012', accountType: 'Current' },
    ],
    whatsappConsent: true,
    reminderCadenceDays: 3,
    maxReminders: 3,
    remindersPaused: false,
    directors: [
      {
        id: 'dir_blue_1',
        name: 'Anita Desai',
        din: '06819203',
        phone: '+91 98250 67890',
        email: 'anita@bluebelltextiles.com',
        aadharNumber: '6712 9012 3412',
        panNumber: 'AADPD4512E',
        bankDetails: 'ICICI Cancel Cheque #349102',
        aadharUploaded: true,
        panUploaded: true,
        bankDocUploaded: true,
        dinDocUploaded: true,
      },
    ],
    attachedDocuments: [
      { id: 'att_bb_1', docKey: 'coa', docName: 'COA', categoryNumber: 1, fileName: 'Bluebell_COA.pdf', fileSize: '1.1 MB', uploadedAt: '2026-08-12', status: 'verified' },
      { id: 'att_bb_2', docKey: 'gst_reg', docName: 'GST registration', categoryNumber: 2, fileName: 'Bluebell_GST.pdf', fileSize: '780 KB', uploadedAt: '2026-08-12', status: 'verified' },
      { id: 'att_bb_4', docKey: 'company_pan', docName: 'Company PAN', categoryNumber: 4, fileName: 'Bluebell_PAN.pdf', fileSize: '390 KB', uploadedAt: '2026-08-12', status: 'verified' },
    ],
  },
];

export const INITIAL_COMPLIANCE_CALENDAR: ComplianceCalendarItem[] = generateStatutoryCalendar(2026, 10);

export const INITIAL_ADHOC_REQUESTS: AdhocRequestItem[] = [
  {
    id: 'adhoc_1',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'GST Amendment etc',
    title: 'Addition of Additional Place of Business in GST Portal',
    description: 'Update warehouse address in Noida Sector 63 on GST portal with rent agreement and NOC.',
    status: 'In Progress',
    priority: 'High',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 4500,
    targetDeadline: '2026-10-08',
    createdAt: '2026-09-28',
    notes: 'Rent agreement verified, awaiting client OTP on registered Aadhaar.',
  },
  {
    id: 'adhoc_2',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'ROC work (Director KYC, Name change, objective amendment, etc)',
    title: 'Annual ROC Director KYC (DIR-3 KYC) for SN Biswas & YX Biswas',
    description: 'Filing of Web-based DIR-3 KYC for both active directors before MCA cutoff.',
    status: 'Review',
    priority: 'Medium',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 3000,
    targetDeadline: '2026-10-10',
    createdAt: '2026-09-25',
    notes: 'Forms prepared, pending CA digital signature verification.',
  },
  {
    id: 'adhoc_3',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    serviceCategory: 'Projected Report',
    title: 'Projected CMA Report & 3-Year Balance Sheet for Working Capital Loan',
    description: 'Bank credit facility expansion report requested by HDFC Bank for ₹2.5 Cr OD limit.',
    status: 'In Progress',
    priority: 'High',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 18000,
    targetDeadline: '2026-10-14',
    createdAt: '2026-09-22',
    notes: 'Draft financial model completed, ratio analysis under review with CA Suraj Dutta.',
  },
  {
    id: 'adhoc_4',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    serviceCategory: 'Trademark',
    title: 'Trademark Class 24 & Class 25 Examination Report Response',
    description: 'Legal reply to examination report raised by Trade Marks Registry Mumbai for logo brand.',
    status: 'Pending',
    priority: 'Medium',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 8500,
    targetDeadline: '2026-10-18',
    createdAt: '2026-09-29',
    notes: 'Prior user affidavit draft being prepared.',
  },
  {
    id: 'adhoc_5',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    serviceCategory: 'PnL and Balancesheet',
    title: 'Provisional PnL & Balance Sheet as of 30th September 2026',
    description: 'Quarterly management accounts for investor board review.',
    status: 'Completed',
    priority: 'Low',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 7500,
    targetDeadline: '2026-09-30',
    completedDate: '2026-09-29',
    createdAt: '2026-09-20',
    notes: 'Signed copies delivered to director SN Biswas.',
  },
  {
    id: 'adhoc_6',
    clientId: 'cli_zylker_01',
    clientName: 'Zylker Agriculture',
    clientGstin: '27AABCS1234D1Z9',
    serviceCategory: 'Startup india registration',
    title: 'DPIIT Startup India Recognition & Section 80-IAC Tax Exemption Application',
    description: 'Application for DPIIT Recognition under AgriTech / Smart Irrigation category with pitch deck dossier and 3-year tax holiday filing.',
    status: 'In Progress',
    priority: 'High',
    assignedStaffName: 'Pooja Verma (Senior Associate)',
    assignedStaffId: 'staff_pooja_02',
    feeQuote: 15000,
    targetDeadline: '2026-10-15',
    createdAt: '2026-10-01',
    notes: 'Entity incorporation verified, pitch deck & Form 1 innovation questionnaire prepared for DPIIT portal submission.',
  },
];

export const INITIAL_PENDING_TAX_7_DAYS: PendingTaxItem[] = [
  {
    id: 'pt_1',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taxType: 'GSTR-1',
    dueDate: '2026-10-05',
    daysRemaining: 5,
    estimatedTaxAmount: 142500,
    status: 'Ready for Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-29',
  },
  {
    id: 'pt_2',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taxType: 'GSTR-1',
    dueDate: '2026-10-05',
    daysRemaining: 5,
    estimatedTaxAmount: 285000,
    status: 'Under Computation',
    registeredPhone: '+919820112345',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-28',
  },
  {
    id: 'pt_3',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taxType: 'TDS Deposit',
    dueDate: '2026-10-07',
    daysRemaining: 7,
    estimatedTaxAmount: 64200,
    status: 'Ready for Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-30',
  },
  {
    id: 'pt_4',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    taxType: 'TDS Deposit',
    dueDate: '2026-10-07',
    daysRemaining: 7,
    estimatedTaxAmount: 48900,
    status: 'Pending Files',
    registeredPhone: '+919825067890',
    assignedStaff: 'Pooja Verma',
    lastReminderSent: '2026-09-27',
  },
];

export const INITIAL_BILLING_INVOICES: BillingInvoiceItem[] = [
  {
    id: 'inv_101',
    invoiceNumber: 'PS/2026-27/0412',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceDescription: 'Monthly GST Compliance & GSTR-3B Retainer (August 2026)',
    serviceCategory: 'Routine GST Filing',
    period: 'August 2026',
    professionalFee: 5000,
    gstAmount: 900,
    totalPayable: 5900,
    invoiceDate: '2026-09-05',
    dueDate: '2026-09-20',
    status: 'Paid',
    paymentMode: 'NEFT / IMPS',
    receiptNumber: 'REC-2026-0391',
  },
  {
    id: 'inv_102',
    invoiceNumber: 'PS/2026-27/0458',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceDescription: 'Provisional PnL and Balance Sheet Preparation & Investor Report',
    serviceCategory: 'Adhoc Service',
    period: 'Q2 FY 2026-27',
    professionalFee: 7500,
    gstAmount: 1350,
    totalPayable: 8850,
    invoiceDate: '2026-09-29',
    dueDate: '2026-10-15',
    status: 'Pending',
  },
  {
    id: 'inv_103',
    invoiceNumber: 'PS/2026-27/0440',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    serviceDescription: 'Statutory Tax Audit u/s 44AB & Form 3CD Compilation',
    serviceCategory: 'Tax Audit',
    period: 'FY 2025-26',
    professionalFee: 35000,
    gstAmount: 6300,
    totalPayable: 41300,
    invoiceDate: '2026-09-15',
    dueDate: '2026-10-05',
    status: 'Pending',
  },
  {
    id: 'inv_104',
    invoiceNumber: 'PS/2026-27/0389',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    serviceDescription: 'Trademark Examination Response Filing Class 24 & 25',
    serviceCategory: 'Adhoc Service',
    period: 'One-Time',
    professionalFee: 8500,
    gstAmount: 1530,
    totalPayable: 10030,
    invoiceDate: '2026-09-28',
    dueDate: '2026-10-12',
    status: 'Pending',
  },
];

export const INITIAL_ACCUMULATED_TASKS_7_DAYS: PendingTaskItem[] = [
  // 1. Statutory Tax Filings
  {
    id: 'task_tax_1',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Filing',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'GSTR-1 Monthly Return Filing (September 2026)',
    taskDescription: 'Finalize and file GSTR-1 outward supplies return on GST portal before statutory cutoff.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'critical',
    estimatedAmount: 142500,
    amountLabel: 'Est. Output Tax',
    status: 'Ready for Filing',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-29',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_2',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Deposit',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'TDS Challan Deposit u/s 194C/194J (September 2026)',
    taskDescription: 'Generate ITNS 281 Challan and ensure client bank payment for TDS deduction on contractor and professional bills.',
    dueDate: '2026-10-07',
    daysRemaining: 5,
    urgency: 'urgent',
    estimatedAmount: 64200,
    amountLabel: 'TDS Payable',
    status: 'Challan Ready',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-30',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_3',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Filing',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taskTitle: 'GSTR-1 Monthly Return Filing (September 2026)',
    taskDescription: 'Review auto-extracted sales register and submit GSTR-1 to prevent e-way bill generation blocking.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'critical',
    estimatedAmount: 285000,
    amountLabel: 'Est. Taxable Base',
    status: 'Under Computation',
    registeredPhone: '+919820112345',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-28',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },
  {
    id: 'task_tax_4',
    sourceSection: 'statutory_tax',
    sourceSectionName: 'Statutory Tax Deposit',
    clientId: 'cli_bluebell_02',
    clientName: 'Bluebell Textiles Pvt Ltd',
    clientGstin: '24AABCB5678B1Z2',
    taskTitle: 'TDS Deposit for September 2026 Deductions',
    taskDescription: 'TDS challan payment required on income-tax portal. Missing salary sheet deduction breakdown.',
    dueDate: '2026-10-07',
    daysRemaining: 5,
    urgency: 'urgent',
    estimatedAmount: 48900,
    amountLabel: 'Est. TDS Due',
    status: 'Pending Files',
    registeredPhone: '+919825067890',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-27',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },

  // 2. GST Document Intake & Upload Queue
  {
    id: 'task_intake_1',
    sourceSection: 'gst_intake',
    sourceSectionName: 'GST Document Intake',
    clientId: 'cli_delta_03',
    clientName: 'Delta Logistics Corp',
    clientGstin: '06AABCD9012C1Z4',
    taskTitle: 'September 2026 GST Invoices & Bank Statements Missing',
    taskDescription: 'Client has not uploaded purchase register and bank statements via portal. 2 reminders already sent.',
    dueDate: '2026-10-04',
    daysRemaining: 2,
    urgency: 'critical',
    status: 'Awaiting Client Uploads',
    registeredPhone: '+919811009988',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-30',
    actionType: 'whatsapp_client',
    targetTab: 'dashboard',
  },

  // 3. Client Workbook Approvals Queue
  {
    id: 'task_approval_1',
    sourceSection: 'client_approval',
    sourceSectionName: 'Client Review & Sign-Off',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'August 2026 Reconciled GST Workbook Sign-Off Pending',
    taskDescription: 'Reconciliation completed. Client has not confirmed the draft GSTR-3B tax liability summary in client portal.',
    dueDate: '2026-10-06',
    daysRemaining: 4,
    urgency: 'urgent',
    status: 'Awaiting Client Confirmation',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    lastReminderSent: '2026-09-28',
    actionType: 'open_portal',
    targetTab: 'client-portal',
  },

  // 4. Billing & Fee Collections
  {
    id: 'task_billing_1',
    sourceSection: 'billing',
    sourceSectionName: 'Billing & Fee Collection',
    clientId: 'cli_apex_01',
    clientName: 'Apex Engineering Works',
    clientGstin: '27AAACA1234A1Z5',
    taskTitle: 'Invoice #PS/2026-27/0440 - Tax Audit Retainer Due',
    taskDescription: 'Professional fee for Statutory Tax Audit FY 2025-26 compilation pending payment.',
    dueDate: '2026-10-05',
    daysRemaining: 3,
    urgency: 'urgent',
    estimatedAmount: 41300,
    amountLabel: 'Fee Payable',
    status: 'Pending Payment',
    registeredPhone: '+919820112345',
    assignedStaff: 'CA Shekhar Das',
    lastReminderSent: '2026-09-29',
    actionType: 'whatsapp_client',
    targetTab: 'billing-finance',
  },
  {
    id: 'task_billing_2',
    sourceSection: 'billing',
    sourceSectionName: 'Billing & Fee Collection',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'Invoice #PS/2026-27/0412 - Routine GST Filing Retainer',
    taskDescription: 'Monthly GST Retainer invoice for August 2026 pending clearance.',
    dueDate: '2026-10-08',
    daysRemaining: 6,
    urgency: 'upcoming',
    estimatedAmount: 5900,
    amountLabel: 'Fee Payable',
    status: 'Pending Payment',
    registeredPhone: '+919873875138',
    assignedStaff: 'CA Shekhar Das',
    lastReminderSent: '2026-09-25',
    actionType: 'whatsapp_client',
    targetTab: 'billing-finance',
  },

  // 5. Adhoc Client Inquiries / Tickets
  {
    id: 'task_adhoc_1',
    sourceSection: 'adhoc',
    sourceSectionName: 'Adhoc Client Request',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    taskTitle: 'GST Additional Place of Business Amendment (Sector 63 Warehouse)',
    taskDescription: 'Rent deed verified. Awaiting client Aadhaar OTP verification to submit amendment on GST portal.',
    dueDate: '2026-10-08',
    daysRemaining: 6,
    urgency: 'urgent',
    estimatedAmount: 4500,
    amountLabel: 'Fee Quote',
    status: 'In Progress (Awaiting OTP)',
    registeredPhone: '+919873875138',
    assignedStaff: 'Pooja Verma (Senior Associate)',
    actionType: 'view_section',
    targetTab: 'adhoc-requests',
  },
];

export const INITIAL_STATUTORY_NOTICES: any[] = [
  {
    id: 'not_gst_01',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    department: 'GST',
    noticeNumber: 'ZA0709260018921',
    noticeDate: '2026-09-24',
    dueDate: '2026-10-14',
    daysRemaining: 9,
    noticeType: 'ASMT-10 (Discrepancy in GSTR-3B vs GSTR-2B Input Tax Credit)',
    status: 'Drafting Reply',
    assignedEmployeeName: 'Pooja Verma (Senior Associate)',
    demandAmount: 48520,
    penaltyAmount: 8734,
    priority: 'Critical',
    responseNotes: 'ITC mismatch of ₹48,520 for FY 2024-25 traced to supplier invoice delayed reporting. GSTR-2B reconciliation attached.',
    documentsCount: 3,
  },
  {
    id: 'not_it_02',
    clientId: 'cli_aggarwal_02',
    clientName: 'Aggarwal & Sons Trading Co.',
    clientGstin: '07AAACA4491E1ZQ',
    department: 'Income Tax',
    noticeNumber: 'ITBA/AST/S/148/2026-27/1049281',
    noticeDate: '2026-09-28',
    dueDate: '2026-10-20',
    daysRemaining: 15,
    noticeType: 'Section 148A(b) - Inquiry on High Value Cash Deposit in Current Account',
    status: 'Under Review',
    assignedEmployeeName: 'CA Shekhar Das (Partner)',
    demandAmount: 185000,
    penaltyAmount: 0,
    priority: 'High',
    responseNotes: 'Cash sales receipts and corresponding VAT/GST returns compiled to establish legitimate business turnover.',
    documentsCount: 6,
  },
  {
    id: 'not_tds_03',
    clientId: 'cli_apex_03',
    clientName: 'Apex Healthtech LLP',
    clientGstin: '07AABFA8941N1Z3',
    department: 'TDS',
    noticeNumber: 'TRACES/DEF/2026/Q1/26Q/091',
    noticeDate: '2026-09-15',
    dueDate: '2026-10-10',
    daysRemaining: 5,
    noticeType: 'Intimation u/s 200A - Short Deduction of 194J Professional Fees',
    status: 'Received',
    assignedEmployeeName: 'Pooja Verma (Senior Associate)',
    demandAmount: 12400,
    penaltyAmount: 2150,
    priority: 'High',
    responseNotes: 'Correction statement 26Q prepared to map valid Lower Deduction Certificate (Form 13).',
    documentsCount: 2,
  },
  {
    id: 'not_roc_04',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    department: 'ROC',
    noticeNumber: 'ROC/DELHI/DIR-3KYC/2026/044',
    noticeDate: '2026-09-30',
    dueDate: '2026-10-05',
    daysRemaining: 0,
    noticeType: 'Deactivation of Director Identification Number (DIN Deactivation Notice)',
    status: 'Replied',
    assignedEmployeeName: 'Pooja Verma (Senior Associate)',
    demandAmount: 5000,
    penaltyAmount: 0,
    priority: 'Medium',
    responseNotes: 'DIR-3 KYC Web challan generated and successfully filed on MCA portal.',
    documentsCount: 1,
  },
];

export const INITIAL_ENTERPRISE_TASKS: any[] = [
  {
    id: 'task_ent_01',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    title: 'GSTR-1 Monthly Return Filing (September 2026)',
    description: 'Verify 142 B2B tax invoices, e-Way bills comparison, and submit GSTR-1 on GSTN portal.',
    serviceType: 'GST',
    priority: 'Urgent',
    status: 'Under Review',
    executorName: 'Pooja Verma',
    reviewerName: 'CA Shekhar Das',
    startDate: '2026-10-01',
    dueDate: '2026-10-11',
    timeSpentHours: 3.5,
    slaHours: 48,
    isOverdue: false,
    checklistItems: [
      { id: 'c1', label: 'Sales register cross-checked with Books', completed: true },
      { id: 'c2', label: 'HSN 6-digit validation completed', completed: true },
      { id: 'c3', label: 'Client confirmation obtained', completed: false },
      { id: 'c4', label: 'EVC/DSC OTP filed on GSTN', completed: false },
    ],
  },
  {
    id: 'task_ent_02',
    clientId: 'cli_aggarwal_02',
    clientName: 'Aggarwal & Sons Trading Co.',
    clientGstin: '07AAACA4491E1ZQ',
    title: 'TDS Challan Deposit ITNS 281 for September Deduction',
    description: 'Deposit ₹48,920 TDS deducted on 194C contractor payments and 194I rent.',
    serviceType: 'TDS',
    priority: 'Urgent',
    status: 'In Progress',
    executorName: 'Pooja Verma',
    reviewerName: 'CA Shekhar Das',
    startDate: '2026-10-02',
    dueDate: '2026-10-07',
    timeSpentHours: 1.2,
    slaHours: 24,
    isOverdue: false,
    checklistItems: [
      { id: 'c1', label: 'TDS deduction register verified', completed: true },
      { id: 'c2', label: 'CIN/BSR Challan counterfoil downloaded', completed: false },
    ],
  },
  {
    id: 'task_ent_03',
    clientId: 'cli_apex_03',
    clientName: 'Apex Healthtech LLP',
    clientGstin: '07AABFA8941N1Z3',
    title: 'Statutory Tax Audit Form 3CD & 3CA Compilation',
    description: 'Verify Section 43B disallowances, MSME 45-day payment compliance, and depreciation schedule.',
    serviceType: 'Audit',
    priority: 'High',
    status: 'In Progress',
    executorName: 'Pooja Verma',
    reviewerName: 'CA Shekhar Das',
    startDate: '2026-09-20',
    dueDate: '2026-10-31',
    timeSpentHours: 14.0,
    slaHours: 120,
    isOverdue: false,
    checklistItems: [
      { id: 'c1', label: 'Trial balance matched with audited ledger', completed: true },
      { id: 'c2', label: 'MSME overdue list extracted & computed', completed: true },
      { id: 'c3', label: 'Partner signature & UDIN generation', completed: false },
    ],
  },
  {
    id: 'task_ent_04',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    clientGstin: '07AABCB9123D1ZX',
    title: 'ASMT-10 Notice Detailed Written Submission Preparation',
    description: 'Prepare clause-by-clause reply to Proper Officer on Input Tax Credit mismatch with supporting invoices.',
    serviceType: 'Litigation',
    priority: 'Urgent',
    status: 'Awaiting Client',
    executorName: 'Pooja Verma',
    reviewerName: 'CA Shekhar Das',
    startDate: '2026-09-26',
    dueDate: '2026-10-14',
    timeSpentHours: 5.5,
    slaHours: 48,
    isOverdue: false,
    checklistItems: [
      { id: 'c1', label: 'Supplier GSTR-1 filing status confirmed', completed: true },
      { id: 'c2', label: 'Bank payment proofs compiled', completed: true },
      { id: 'c3', label: 'Affidavit from client signed', completed: false },
    ],
  },
];

export const INITIAL_TIMESHEETS: any[] = [
  {
    id: 'ts_01',
    employeeId: 'staff_pooja_02',
    employeeName: 'Pooja Verma',
    taskId: 'task_ent_01',
    taskTitle: 'GSTR-1 Monthly Return Filing',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceCategory: 'GST Compliance',
    date: '2026-10-05',
    hoursSpent: 3.5,
    isBillable: true,
    workSummary: 'Extracted and verified 142 B2B invoices using Gemini Vision AI. Reconciled tax amounts.',
    status: 'Submitted',
  },
  {
    id: 'ts_02',
    employeeId: 'staff_pooja_02',
    employeeName: 'Pooja Verma',
    taskId: 'task_ent_02',
    taskTitle: 'TDS Challan Deposit ITNS 281',
    clientId: 'cli_aggarwal_02',
    clientName: 'Aggarwal & Sons Trading Co.',
    serviceCategory: 'TDS Compliance',
    date: '2026-10-05',
    hoursSpent: 1.5,
    isBillable: true,
    workSummary: 'Compiled September contractor deductions and initiated tax challan batch.',
    status: 'Approved',
  },
  {
    id: 'ts_03',
    employeeId: 'ca_rajesh_01',
    employeeName: 'CA Shekhar Das',
    taskId: 'task_ent_04',
    taskTitle: 'ASMT-10 Notice Written Submission',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    serviceCategory: 'Tax Litigation',
    date: '2026-10-04',
    hoursSpent: 2.0,
    isBillable: true,
    workSummary: 'Drafted legal jurisprudence reply on section 16(2)(c) ITC admissibility.',
    status: 'Approved',
  },
];

export const INITIAL_DSC_LICENCES: any[] = [
  {
    id: 'dsc_01',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    holderName: 'SN Biswas',
    holderDesignation: 'Managing Director',
    holderPan: 'ABCDB1234F',
    certType: 'Class 3 DSC (Signing)',
    issuer: 'eMudhra Ltd',
    validFrom: '2024-10-25',
    expiryDate: '2026-10-25',
    daysToExpiry: 20,
    status: 'Expiring Soon',
    storageLocation: 'Token Safe Locker #B-12 (ePass 2003)',
    renewalStatus: 'In Process',
  },
  {
    id: 'dsc_02',
    clientId: 'cli_aggarwal_02',
    clientName: 'Aggarwal & Sons Trading Co.',
    holderName: 'Ramesh Aggarwal',
    holderDesignation: 'Partner',
    holderPan: 'AAAPA1092P',
    certType: 'Class 3 DSC (Combo)',
    issuer: 'Capricorn Identity Services',
    validFrom: '2024-10-12',
    expiryDate: '2026-10-12',
    daysToExpiry: 7,
    status: 'Expiring Soon',
    storageLocation: 'Vault Slot #A-04 (Watchdata ProxKey)',
    renewalStatus: 'Documents Collected',
  },
  {
    id: 'dsc_03',
    clientId: 'cli_apex_03',
    clientName: 'Apex Healthtech LLP',
    holderName: 'Dr. Sunita Rao',
    holderDesignation: 'Designated Partner',
    holderPan: 'BAPPR8841M',
    certType: 'DIN',
    issuer: 'Ministry of Corporate Affairs (MCA)',
    validFrom: '2021-04-10',
    expiryDate: '2027-04-10',
    daysToExpiry: 187,
    status: 'Active',
    storageLocation: 'MCA Portal Master Data',
    renewalStatus: 'Not Started',
  },
  {
    id: 'dsc_04',
    clientId: 'cli_briopox_01',
    clientName: 'Briopox Pvt Ltd',
    holderName: 'Briopox Pvt Ltd Factory',
    holderDesignation: 'Company Licence',
    holderPan: 'ABCDB1234F',
    certType: 'FSSAI',
    issuer: 'Food Safety and Standards Authority of India',
    validFrom: '2023-11-01',
    expiryDate: '2026-11-01',
    daysToExpiry: 27,
    status: 'Expiring Soon',
    storageLocation: 'Statutory File Folder #12',
    renewalStatus: 'Not Started',
  },
];

export const INITIAL_WORKFLOW_AUTOMATIONS: any[] = [
  {
    id: 'wf_01',
    name: '1st of Month GST Document Intake & Follow-up',
    description: 'Auto-scans active GST clients on 1st of every month, generates secure upload links, dispatches WhatsApp request, and checks uploads.',
    category: 'GST Intake',
    triggerType: 'Monthly 1st',
    status: 'Active',
    lastRunAt: '2026-10-01 09:00 AM',
    totalRuns: 48,
    successRatePercent: 98.5,
    steps: [
      { type: 'TRIGGER', title: 'Schedule: 1st of Every Month at 09:00 AM', details: 'Triggers for all active regular GST clients.' },
      { type: 'ACTION', title: 'Dispatch WhatsApp Intake Request', details: 'Sends prefilled checklist for Sales, Purchase, Bank & Debit/Credit notes.' },
      { type: 'WAIT', title: 'Wait 3 Days', details: 'Awaiting client document uploads to portal.' },
      { type: 'CONDITION', title: 'Check If Documents Received', details: 'Evaluates required checklist categories.' },
      { type: 'ACTION', title: 'Send Automated Polite Reminder (Day 3 & 5)', details: 'Highlights exact missing document categories.' },
      { type: 'ESCALATION', title: 'Escalate to Partner & Assign Call Task', details: 'Triggers priority desk task if pending beyond Day 7.' },
    ],
  },
  {
    id: 'wf_02',
    name: 'Statutory Notice Immediate CA Alert & Client Acknowledgment',
    description: 'When new ASMT-10, 148A, or TRACES notice is logged, automatically tags priority, logs timeline, and generates draft reply.',
    category: 'Notice Escalation',
    triggerType: 'Notice Uploaded',
    status: 'Active',
    lastRunAt: '2026-09-30 04:15 PM',
    totalRuns: 19,
    successRatePercent: 100,
    steps: [
      { type: 'TRIGGER', title: 'Statutory Notice Created', details: 'Detects notice entry across GST, Income Tax, TDS, ROC.' },
      { type: 'ACTION', title: 'Extract Demand & Due Date via AI', details: 'Gemini Vision AI extracts Section, Demand Amount, Due Date.' },
      { type: 'APPROVAL', title: 'Human Approval Gate', details: 'Requires CA Partner review before formal external dispatch.' },
      { type: 'ACTION', title: 'Client WhatsApp/Email Briefing', details: 'Informs client that notice has been noted and work initiated.' },
    ],
  },
  {
    id: 'wf_03',
    name: 'Statutory Tax Audit 45-Day MSME Payment Monitor',
    description: 'Analyzes purchase registers and vendor ledgers to identify supplier payments exceeding 15/45 days under Section 43B(h).',
    category: 'Tax Reminder',
    triggerType: 'Statutory Due Date',
    status: 'Active',
    lastRunAt: '2026-10-04 11:30 AM',
    totalRuns: 32,
    successRatePercent: 96.8,
    steps: [
      { type: 'TRIGGER', title: 'Audit Working Paper Computation', details: 'Runs during monthly or annual book closing.' },
      { type: 'CONDITION', title: 'Identify MSME Overdue Ledgers', details: 'Flags unpaid MSME vendor balances exceeding statutory limit.' },
      { type: 'ACTION', title: 'Generate Exception Advisory Report', details: 'Calculates disallowable expenditure and tax liability impact.' },
    ],
  },
];

export const INITIAL_AI_AGENT_ACTIONS: any[] = [
  {
    id: 'ai_act_01',
    timestamp: '2026-10-05 10:14 AM',
    agentName: 'Document Agent',
    actionTitle: 'Classified & Extracted 142 B2B Tax Invoices',
    riskLevel: 'READ ONLY',
    status: 'Auto Executed',
    summary: 'Processed 142 invoices for Briopox Pvt Ltd. Detected 1 duplicate invoice (#INV-8891) and verified GSTIN place of supply.',
    targetEntity: 'Briopox Pvt Ltd',
    proposedChanges: '142 line items committed to database. 1 exception flagged for reviewer.',
  },
  {
    id: 'ai_act_02',
    timestamp: '2026-10-05 09:30 AM',
    agentName: 'Follow-Up Agent',
    actionTitle: 'Prepared Day-3 WhatsApp Intake Reminder Batch',
    riskLevel: 'SENSITIVE',
    status: 'Pending Approval',
    summary: 'Identified 8 clients with pending September bank statements. Prepared personalized reminder copy with upload links.',
    targetEntity: '8 Active GST Clients',
    proposedChanges: 'Requires Partner confirmation before bulk WhatsApp API dispatch to 8 registered mobile numbers.',
  },
  {
    id: 'ai_act_03',
    timestamp: '2026-10-04 05:45 PM',
    agentName: 'Reconciliation Agent',
    actionTitle: 'GSTR-2B vs Purchase Register 100% Deterministic Match',
    riskLevel: 'READ ONLY',
    status: 'Auto Executed',
    summary: 'Matched ₹14.85 Lakhs ITC. Identified ₹48,520 supplier delay where vendor filed late. Zero arithmetic discrepancies.',
    targetEntity: 'Briopox Pvt Ltd (August 2026)',
    proposedChanges: 'Generated Working Paper Sheet 7 in generated workbook.',
  },
  {
    id: 'ai_act_04',
    timestamp: '2026-10-04 02:10 PM',
    agentName: 'Notice Agent',
    actionTitle: 'ASMT-10 Notice Legal Defense Brief Prepared',
    riskLevel: 'LOW RISK',
    status: 'Approved & Executed',
    summary: 'Analyzed notice ZA0709260018921. Generated citations for Bharti Airtel and Union of India on valid ITC entitlement.',
    targetEntity: 'Briopox Pvt Ltd',
    proposedChanges: 'Draft reply stored in Notice Vault ready for Partner digital signature.',
  },
];

export const INITIAL_SUPER_ADMIN_TENANTS: any[] = [
  {
    id: 'ten_01',
    firmName: 'Das & Associates Chartered Accountants',
    slug: 'das-associates',
    planName: 'AI Automation',
    status: 'Active',
    usersCount: 8,
    clientsCount: 42,
    storageMb: 1420,
    aiTokensUsed: 184500,
    whatsappMessagesSent: 840,
    mrrAmount: 9999,
    renewalDate: '2027-04-01',
    contactPerson: 'CA Shekhar Das',
    contactEmail: 'shekhar@quinceautomation.com',
  },
  {
    id: 'ten_02',
    firmName: 'Kapoor & Singhania Advisory LLP',
    slug: 'kapoor-singhania',
    planName: 'Professional',
    status: 'Active',
    usersCount: 4,
    clientsCount: 28,
    storageMb: 890,
    aiTokensUsed: 92400,
    whatsappMessagesSent: 410,
    mrrAmount: 4999,
    renewalDate: '2026-12-15',
    contactPerson: 'CA Rajiv Kapoor',
    contactEmail: 'rajiv@kapoorsinghania.in',
  },
  {
    id: 'ten_03',
    firmName: 'Mehta Corporate Tax Consultants',
    slug: 'mehta-tax',
    planName: 'Starter',
    status: 'Trial',
    usersCount: 2,
    clientsCount: 12,
    storageMb: 340,
    aiTokensUsed: 24000,
    whatsappMessagesSent: 150,
    mrrAmount: 1999,
    renewalDate: '2026-10-18',
    contactPerson: 'Sanjay Mehta',
    contactEmail: 'sanjay@mehtatax.com',
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: any[] = [
  {
    id: 'plan_starter',
    name: 'Starter Plan',
    code: 'starter',
    priceMonthly: 1999,
    priceYearly: 19990,
    maxUsers: 2,
    maxClients: 20,
    maxStorageGb: 5,
    aiCredits: 500,
    whatsappCredits: 500,
    supportLevel: 'Email Support (48h SLA)',
    features: ['Routine GST Pipeline', 'Client Portal (Token Auth)', 'Statutory Compliance Calendar', 'Excel Working Paper Engine'],
  },
  {
    id: 'plan_pro',
    name: 'Professional Practice',
    code: 'professional',
    priceMonthly: 4999,
    priceYearly: 49990,
    maxUsers: 5,
    maxClients: 60,
    maxStorageGb: 20,
    aiCredits: 2000,
    whatsappCredits: 2500,
    supportLevel: 'Priority WhatsApp & Phone Support (12h SLA)',
    features: ['All Starter Features', 'Adhoc Service Desk', 'Billing & Finance Invoicing', 'Notice & Litigation Vault', 'Baileys Open-Source WhatsApp Linking'],
  },
  {
    id: 'plan_ai_auto',
    name: 'AI Automation & Agents',
    code: 'ai_automation',
    priceMonthly: 9999,
    priceYearly: 99990,
    maxUsers: 15,
    maxClients: 200,
    maxStorageGb: 100,
    aiCredits: 10000,
    whatsappCredits: 10000,
    supportLevel: 'Dedicated Relationship Manager (4h SLA)',
    features: ['All Pro Features', 'Gemini Multimodal Vision Extraction', 'AI CA Copilot Natural Language Assistant', '8 Specialized AI Agents with Safety Gate', 'Visual No-Code Workflow Builder', 'DSC & Licence Expiry Radar'],
  },
  {
    id: 'plan_enterprise',
    name: 'Enterprise Dedicated / On-Premise',
    code: 'enterprise',
    priceMonthly: 24999,
    priceYearly: 249990,
    maxUsers: 999,
    maxClients: 9999,
    maxStorageGb: 1000,
    aiCredits: 100000,
    whatsappCredits: 50000,
    supportLevel: '24/7 Dedicated Technical Architect & 99.9% Uptime SLA',
    features: ['All AI Automation Features', 'Dedicated Private Database & Storage VPC', 'White-Label Branding & Custom Domain (portal.firm.in)', 'Custom API & Tally/ERP Bi-directional Sync', 'SSO & Enterprise Role Permissions'],
  },
];

