// src/db/seed.ts
import { db } from './index.ts';
import {
  users,
  clients,
  monthlyRequests,
  documentFiles,
  extractedDocuments,
  extractedLineItems,
  bankTransactions,
  validationExceptions,
  generatedWorkbooks,
  auditNotifications,
} from './schema.ts';
import { generateSecureToken } from '../services/scheduler.ts';
import { generateMonthlyRequestMessage, createWhatsAppDeepLink } from '../services/messagingService.ts';

export async function seedInitialData() {
  console.log('Seeding initial data for Professional Samadhan...');

  // 1. Seed Users
  await db.insert(users).values([
    {
      id: 'ca_rajesh_01',
      email: 'rajesh.sharma@professionalsamadhan.in',
      displayName: 'CA Rajesh Sharma (FCA)',
      role: 'ca_admin',
      phone: '+919820011111',
      active: true,
      assignedClientIds: ['cli_apex_01', 'cli_bluebell_02', 'cli_zenith_03', 'cli_zenith_04'],
    },
    {
      id: 'staff_pooja_02',
      email: 'pooja.verma@professionalsamadhan.in',
      displayName: 'Pooja Verma (Senior Associate)',
      role: 'staff',
      phone: '+919820022222',
      active: true,
      assignedClientIds: ['cli_apex_01', 'cli_bluebell_02'],
    },
    {
      id: 'staff_amit_03',
      email: 'amit.patel@professionalsamadhan.in',
      displayName: 'Amit Patel (GST Assistant)',
      role: 'staff',
      phone: '+919820033333',
      active: true,
      assignedClientIds: ['cli_zenith_03', 'cli_zenith_04'],
    },
  ]).onConflictDoNothing();

  // 2. Seed Clients
  await db.insert(clients).values([
    {
      id: 'cli_apex_01',
      businessName: 'Apex Engineering Works',
      contactPerson: 'Suresh Mehta',
      gstin: '27AAACA1234A1Z5',
      registeredPhone: '+919820112345',
      email: 'accounts@apexengineering.in',
      assignedStaffId: 'staff_pooja_02',
      assignedStaffName: 'Pooja Verma',
      active: true,
      requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements', 'debit_credit_notes'],
      expectedBankAccounts: [
        { bankName: 'HDFC Bank', accountNumber: '50200012345678', ifsc: 'HDFC0000123', accountType: 'Current' },
      ],
      whatsappConsent: true,
      reminderCadenceDays: 3,
      maxReminders: 3,
      remindersPaused: false,
    },
    {
      id: 'cli_bluebell_02',
      businessName: 'Bluebell Textiles Pvt Ltd',
      contactPerson: 'Anita Desai',
      gstin: '24AABCB5678B1Z2',
      registeredPhone: '+919825067890',
      email: 'finance@bluebelltextiles.com',
      assignedStaffId: 'staff_pooja_02',
      assignedStaffName: 'Pooja Verma',
      active: true,
      requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
      expectedBankAccounts: [
        { bankName: 'ICICI Bank Ltd', accountNumber: '001205009876', ifsc: 'ICIC0000012', accountType: 'Current' },
      ],
      whatsappConsent: true,
      reminderCadenceDays: 3,
      maxReminders: 3,
      remindersPaused: false,
    },
    {
      id: 'cli_zenith_03',
      businessName: 'Zenith Healthcare Supplies',
      contactPerson: 'Dr. Vikram Joshi',
      gstin: '27AABCZ9988C1Z4',
      registeredPhone: '+919820233445',
      email: 'dr.joshi@zenithhealth.in',
      assignedStaffId: 'staff_amit_03',
      assignedStaffName: 'Amit Patel',
      active: true,
      requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
      expectedBankAccounts: [
        { bankName: 'State Bank of India', accountNumber: '30124567890', ifsc: 'SBIN0001234', accountType: 'Current' },
      ],
      whatsappConsent: true,
      reminderCadenceDays: 3,
      maxReminders: 3,
      remindersPaused: false,
    },
    {
      id: 'cli_zenith_04',
      businessName: 'Zenith Diagnostics Lab',
      contactPerson: 'Dr. Vikram Joshi',
      gstin: '27AABCZ9988D1Z3',
      registeredPhone: '+919820233445', // Shared phone number demonstrating multi-business selection
      email: 'lab@zenithhealth.in',
      assignedStaffId: 'staff_amit_03',
      assignedStaffName: 'Amit Patel',
      active: true,
      requiredChecklist: ['sales_invoices', 'purchase_invoices', 'bank_statements'],
      expectedBankAccounts: [
        { bankName: 'State Bank of India', accountNumber: '30124567891', ifsc: 'SBIN0001234', accountType: 'Current' },
      ],
      whatsappConsent: true,
      reminderCadenceDays: 3,
      maxReminders: 3,
      remindersPaused: false,
    },
  ]).onConflictDoNothing();

  // 3. Monthly Requests for August 2026
  const tokenApex = 'token_apex_aug2026_demo_77a';
  const tokenBluebell = 'token_bluebell_aug2026_demo_88b';
  const tokenZenith1 = 'token_zenith1_aug2026_demo_99c';
  const tokenZenith2 = 'token_zenith2_aug2026_demo_11d';

  const expDate = new Date();
  expDate.setDate(expDate.getDate() + 25);

  await db.insert(monthlyRequests).values([
    {
      id: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      reportingMonth: 'August 2026',
      year: 2026,
      monthNumber: 8,
      status: 'Needs Review',
      secureUploadToken: tokenApex,
      tokenExpiresAt: expDate,
      reminderCount: 1,
      totalFilesReceived: 4,
      totalInvoicesExtracted: 5,
      unresolvedExceptionsCount: 1,
      activeWorkbookVersion: 1,
    },
    {
      id: 'req_bluebell_2026_08',
      clientId: 'cli_bluebell_02',
      reportingMonth: 'August 2026',
      year: 2026,
      monthNumber: 8,
      status: 'Awaiting Client Confirmation',
      secureUploadToken: tokenBluebell,
      tokenExpiresAt: expDate,
      reminderCount: 0,
      totalFilesReceived: 3,
      totalInvoicesExtracted: 4,
      unresolvedExceptionsCount: 0,
      activeWorkbookVersion: 1,
    },
    {
      id: 'req_zenith_2026_08',
      clientId: 'cli_zenith_03',
      reportingMonth: 'August 2026',
      year: 2026,
      monthNumber: 8,
      status: 'Missing Documents',
      secureUploadToken: tokenZenith1,
      tokenExpiresAt: expDate,
      reminderCount: 2,
      totalFilesReceived: 1,
      totalInvoicesExtracted: 1,
      unresolvedExceptionsCount: 2,
      activeWorkbookVersion: 0,
    },
    {
      id: 'req_zenith_lab_2026_08',
      clientId: 'cli_zenith_04',
      reportingMonth: 'August 2026',
      year: 2026,
      monthNumber: 8,
      status: 'Requested',
      secureUploadToken: tokenZenith2,
      tokenExpiresAt: expDate,
      reminderCount: 0,
      totalFilesReceived: 0,
      totalInvoicesExtracted: 0,
      unresolvedExceptionsCount: 0,
      activeWorkbookVersion: 0,
    },
  ]).onConflictDoNothing();

  // 4. Document Files for Apex
  await db.insert(documentFiles).values([
    {
      id: 'doc_apex_file_01',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      reportingPeriod: 'August 2026',
      originalFilename: 'Apex_Sales_Invoices_Aug26.pdf',
      storagePath: '/uploads/cli_apex_01/Apex_Sales_Invoices_Aug26.pdf',
      fileHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      mimeType: 'application/pdf',
      sizeBytes: 421800,
      source: 'client_portal',
      uploaderName: 'Suresh Mehta (Client)',
      status: 'processed',
      scanMethod: 'native_pdf',
    },
    {
      id: 'doc_apex_file_02',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      reportingPeriod: 'August 2026',
      originalFilename: 'Raw_Material_Purchase_Bills.pdf',
      storagePath: '/uploads/cli_apex_01/Raw_Material_Purchase_Bills.pdf',
      fileHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      mimeType: 'application/pdf',
      sizeBytes: 890400,
      source: 'client_portal',
      uploaderName: 'Suresh Mehta (Client)',
      status: 'processed',
      scanMethod: 'paddle_ocr',
    },
    {
      id: 'doc_apex_file_03',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      reportingPeriod: 'August 2026',
      originalFilename: 'HDFC_Bank_Statement_Aug2026.csv',
      storagePath: '/uploads/cli_apex_01/HDFC_Bank_Statement_Aug2026.csv',
      fileHash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
      mimeType: 'text/csv',
      sizeBytes: 15400,
      source: 'client_portal',
      uploaderName: 'Suresh Mehta (Client)',
      status: 'processed',
      scanMethod: 'spreadsheet_parse',
    },
    {
      id: 'doc_apex_file_04',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      reportingPeriod: 'August 2026',
      originalFilename: 'Credit_Note_Kiran_Tooling.jpg',
      storagePath: '/uploads/cli_apex_01/Credit_Note_Kiran_Tooling.jpg',
      fileHash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
      mimeType: 'image/jpeg',
      sizeBytes: 310500,
      source: 'whatsapp_webhook',
      uploaderName: 'WhatsApp +91 98201 12345',
      status: 'processed',
      scanMethod: 'paddle_ocr',
    },
  ]).onConflictDoNothing();

  // 5. Extracted Document Units for Apex
  await db.insert(extractedDocuments).values([
    {
      id: 'ext_apex_sales_01',
      documentFileId: 'doc_apex_file_01',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      docType: 'sales_invoice',
      docNumber: 'INV/26-27/041',
      docDate: '2026-08-05',
      supplierName: 'Apex Engineering Works',
      supplierGstin: '27AAACA1234A1Z5',
      buyerName: 'Bharat Forge Automation Ltd',
      buyerGstin: '27AABCB4321A1Z9',
      placeOfSupply: '27-Maharashtra',
      taxableAmount: '120000.00',
      cgstAmount: '10800.00',
      sgstAmount: '10800.00',
      igstAmount: '0.00',
      totalAmount: '141600.00',
      extractionConfidence: '98.50',
      reviewStatus: 'verified',
    },
    {
      id: 'ext_apex_sales_02',
      documentFileId: 'doc_apex_file_01',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      docType: 'sales_invoice',
      docNumber: 'INV/26-27/044', // Note: Gap between 041 and 044 triggers sequence gap check
      docDate: '2026-08-20',
      supplierName: 'Apex Engineering Works',
      supplierGstin: '27AAACA1234A1Z5',
      buyerName: 'Tata Auto Components',
      buyerGstin: '27AABCT1234D1Z8',
      placeOfSupply: '27-Maharashtra',
      taxableAmount: '185000.00',
      cgstAmount: '16650.00',
      sgstAmount: '16650.00',
      igstAmount: '0.00',
      totalAmount: '218300.00',
      extractionConfidence: '99.00',
      reviewStatus: 'verified',
    },
    {
      id: 'ext_apex_purch_01',
      documentFileId: 'doc_apex_file_02',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      docType: 'purchase_invoice',
      docNumber: 'PUR/2026/891',
      docDate: '2026-08-10',
      supplierName: 'Shree Steel Suppliers & Hardware',
      supplierGstin: '27AAACS9988E1Z1',
      buyerName: 'Apex Engineering Works',
      buyerGstin: '27AAACA1234A1Z5',
      placeOfSupply: '27-Maharashtra',
      taxableAmount: '80000.00',
      cgstAmount: '7200.00',
      sgstAmount: '7200.00',
      igstAmount: '0.00',
      totalAmount: '94400.00',
      extractionConfidence: '96.20',
      reviewStatus: 'verified',
    },
    {
      id: 'ext_apex_purch_02',
      documentFileId: 'doc_apex_file_02',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      docType: 'purchase_invoice',
      docNumber: 'INV-GUJ-904',
      docDate: '2026-08-16',
      supplierName: 'Reliance Petrochem Ltd (Gujarat)',
      supplierGstin: '24AABCR1234F1Z8',
      buyerName: 'Apex Engineering Works',
      buyerGstin: '27AAACA1234A1Z5',
      placeOfSupply: '24-Gujarat',
      taxableAmount: '55000.00',
      cgstAmount: '0.00',
      sgstAmount: '0.00',
      igstAmount: '9900.00',
      totalAmount: '64900.00',
      extractionConfidence: '97.00',
      reviewStatus: 'verified',
    },
    {
      id: 'ext_apex_crnote_01',
      documentFileId: 'doc_apex_file_04',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      gstin: '27AAACA1234A1Z5',
      docType: 'credit_note',
      docNumber: 'CN/26-27/004',
      docDate: '2026-08-25',
      supplierName: 'Kiran Tooling Corp',
      supplierGstin: '27AAACK4499P1ZZ',
      buyerName: 'Apex Engineering Works',
      buyerGstin: '27AAACA1234A1Z5',
      originalInvoiceRef: 'PUR/2026/891',
      placeOfSupply: '27-Maharashtra',
      taxableAmount: '10000.00',
      cgstAmount: '900.00',
      sgstAmount: '900.00',
      igstAmount: '0.00',
      totalAmount: '11800.00',
      extractionConfidence: '95.50',
      reviewStatus: 'auto_extracted',
    },
  ]).onConflictDoNothing();

  // 6. Extracted Line Items
  await db.insert(extractedLineItems).values([
    {
      id: 'li_apex_01',
      documentUnitId: 'ext_apex_sales_01',
      itemDescription: 'High Tensile Machine Fasteners M16x50mm',
      hsnSac: '7318',
      quantity: '400.00',
      unit: 'NOS',
      rate: '300.00',
      taxableValue: '120000.00',
      taxRatePercent: '18.00',
      cgstAmount: '10800.00',
      sgstAmount: '10800.00',
      igstAmount: '0.00',
      totalAmount: '141600.00',
    },
    {
      id: 'li_apex_02',
      documentUnitId: 'ext_apex_sales_02',
      itemDescription: 'Hydraulic Cylinder Rod Assembly Model HCR-40',
      hsnSac: '8412',
      quantity: '10.00',
      unit: 'SETS',
      rate: '18500.00',
      taxableValue: '185000.00',
      taxRatePercent: '18.00',
      cgstAmount: '16650.00',
      sgstAmount: '16650.00',
      igstAmount: '0.00',
      totalAmount: '218300.00',
    },
    {
      id: 'li_apex_03',
      documentUnitId: 'ext_apex_purch_01',
      itemDescription: 'Alloy Steel Round Bars 50mm dia Grade EN-24',
      hsnSac: '7228',
      quantity: '1000.00',
      unit: 'KGS',
      rate: '80.00',
      taxableValue: '80000.00',
      taxRatePercent: '18.00',
      cgstAmount: '7200.00',
      sgstAmount: '7200.00',
      igstAmount: '0.00',
      totalAmount: '94400.00',
    },
    {
      id: 'li_apex_04',
      documentUnitId: 'ext_apex_purch_02',
      itemDescription: 'Polymer Extrusion Granules Grade HDPE-60',
      hsnSac: '3901',
      quantity: '500.00',
      unit: 'KGS',
      rate: '110.00',
      taxableValue: '55000.00',
      taxRatePercent: '18.00',
      cgstAmount: '0.00',
      sgstAmount: '0.00',
      igstAmount: '9900.00',
      totalAmount: '64900.00',
    },
  ]).onConflictDoNothing();

  // 7. Bank Transactions
  await db.insert(bankTransactions).values([
    {
      id: 'tx_apex_01',
      documentUnitId: 'ext_apex_sales_01',
      monthlyRequestId: 'req_apex_2026_08',
      bankName: 'HDFC Bank',
      accountNumber: '50200012345678',
      transactionDate: '2026-08-04',
      narration: 'NEFT CR-BHARAT FORGE AUTOMATION-INVOICE SETTL',
      referenceNumber: 'NEFT00293847',
      debitAmount: '0.00',
      creditAmount: '141600.00',
      balance: '345000.00',
    },
    {
      id: 'tx_apex_02',
      documentUnitId: 'ext_apex_purch_01',
      monthlyRequestId: 'req_apex_2026_08',
      bankName: 'HDFC Bank',
      accountNumber: '50200012345678',
      transactionDate: '2026-08-11',
      narration: 'RTGS DR-SHREE STEEL SUPPLIERS PUNE',
      referenceNumber: 'RTGS99283741',
      debitAmount: '94400.00',
      creditAmount: '0.00',
      balance: '250600.00',
    },
    {
      id: 'tx_apex_03',
      documentUnitId: 'ext_apex_purch_02',
      monthlyRequestId: 'req_apex_2026_08',
      bankName: 'HDFC Bank',
      accountNumber: '50200012345678',
      transactionDate: '2026-08-18',
      narration: 'NEFT DR-RELIANCE PETROCHEM LTD GUJARAT',
      referenceNumber: 'NEFT88492011',
      debitAmount: '64900.00',
      creditAmount: '0.00',
      balance: '185700.00',
    },
    {
      id: 'tx_apex_04',
      documentUnitId: 'ext_apex_sales_02',
      monthlyRequestId: 'req_apex_2026_08',
      bankName: 'HDFC Bank',
      accountNumber: '50200012345678',
      transactionDate: '2026-08-25',
      narration: 'RTGS CR-TATA AUTO COMPONENTS PART PYMT',
      referenceNumber: 'RTGS11094821',
      debitAmount: '0.00',
      creditAmount: '200000.00',
      balance: '385700.00',
    },
  ]).onConflictDoNothing();

  // 8. Validation Exceptions for Apex
  await db.insert(validationExceptions).values([
    {
      id: 'ex_apex_01',
      monthlyRequestId: 'req_apex_2026_08',
      documentFileId: 'doc_apex_file_01',
      documentUnitId: 'ext_apex_sales_02',
      severity: 'info',
      checkType: 'sequence_gap',
      message: 'Possible invoice sequence gap between INV/26-27/041 and INV/26-27/044 (2 missing invoice numbers 042, 043). Verified if cancelled or issued in another branch.',
      details: { gapStart: 41, gapEnd: 44, missingCount: 2 },
      resolved: false,
    },
  ]).onConflictDoNothing();

  // 9. Generated Workbook for Bluebell
  await db.insert(generatedWorkbooks).values([
    {
      id: 'wb_bluebell_v1',
      monthlyRequestId: 'req_bluebell_2026_08',
      clientId: 'cli_bluebell_02',
      gstin: '24AABCB5678B1Z2',
      reportingPeriod: 'August 2026',
      version: 1,
      filename: 'Bluebell_Textiles_Pvt_Ltd_24AABCB5678B1Z2_August_2026_v1.xlsx',
      filePath: '/workbooks/cli_bluebell_02/Bluebell_Textiles_Pvt_Ltd_24AABCB5678B1Z2_August_2026_v1.xlsx',
      status: 'awaiting_client_confirmation',
      generatedBy: 'Pooja Verma (Senior Associate)',
    },
  ]).onConflictDoNothing();

  // 10. Audit notifications
  await db.insert(auditNotifications).values([
    {
      id: 'aud_seed_01',
      monthlyRequestId: 'req_apex_2026_08',
      clientId: 'cli_apex_01',
      eventType: 'request_prepared',
      channel: 'whatsapp_manual',
      recipient: '+919820112345',
      messageBody: generateMonthlyRequestMessage({
        reportingMonth: 'August 2026',
        secureUploadLink: `https://professionalsamadhan.in/client-portal?token=${tokenApex}`,
      }),
      status: 'prepared',
      details: { mode: 'manual', note: 'Prepared on 1st Aug 2026 9:00 AM Asia/Kolkata' },
    },
    {
      id: 'aud_seed_02',
      monthlyRequestId: 'req_bluebell_2026_08',
      clientId: 'cli_bluebell_02',
      eventType: 'workbook_generated',
      channel: 'whatsapp_manual',
      recipient: '+919825067890',
      messageBody: `Dear Anita Desai,\n\nYour GST working paper and compiled Excel workbook (v1) for August 2026 is now ready for your review.\nPlease review and approve: https://professionalsamadhan.in/client-portal?token=${tokenBluebell}`,
      status: 'prepared',
      details: { mode: 'manual', version: 1 },
    },
  ]).onConflictDoNothing();

  console.log('Seeding completed successfully!');
}
