// src/types/index.ts

export type UserRole = 'ca_admin' | 'staff' | 'client';

export type MonthlyRequestStatus =
  | 'Requested'
  | 'Awaiting Uploads'
  | 'Processing'
  | 'Missing Documents'
  | 'Needs Review'
  | 'Awaiting Client Confirmation'
  | 'Corrections Requested'
  | 'Client Confirmed'
  | 'CA Approved';

export interface DirectorKYC {
  id: string;
  name: string;
  din?: string;
  phone?: string;
  email?: string;
  aadharNumber?: string;
  panNumber?: string;
  bankDetails?: string; // cancel cheque ref
  aadharUploaded?: boolean;
  panUploaded?: boolean;
  bankDocUploaded?: boolean;
  dinDocUploaded?: boolean;
}

export interface ClientAttachedDoc {
  id: string;
  docKey: string;
  docName: string;
  categoryNumber: number;
  fileName?: string;
  fileSize?: string;
  uploadedAt?: string;
  status: 'uploaded' | 'pending' | 'verified';
  expiryDate?: string;
  notes?: string;
}

export interface Client {
  id: string;
  businessName: string;
  contactPerson: string;
  gstin: string;
  cin?: string;
  address?: string;
  registeredPhone: string;
  email: string;
  assignedStaffId?: string;
  assignedStaffName?: string;
  active: boolean;
  directors?: DirectorKYC[];
  attachedDocuments?: ClientAttachedDoc[];
  requiredChecklist: string[];
  expectedBankAccounts: Array<{
    bankName: string;
    accountNumber: string;
    ifsc?: string;
    accountType?: string;
  }>;
  whatsappConsent: boolean;
  whatsappConsentDate?: string;
  reminderCadenceDays: number;
  maxReminders: number;
  remindersPaused: boolean;
  googleDriveFolderId?: string;
  googleDriveUrl?: string;
}

export type AdhocServiceCategory =
  | 'GST Registration'
  | 'GST Amendment etc'
  | 'Company Registration'
  | 'Trademark'
  | 'FSSAI'
  | 'ROC work (Director KYC, Name change, objective amendment, etc)'
  | 'MSME registration'
  | 'Startup india registration'
  | 'Professional tax'
  | 'Projected Report'
  | 'PnL and Balancesheet'
  | 'Income Tax Notice Reply'
  | 'Other Advisory';

export interface AdhocRequestItem {
  id: string;
  clientId: string;
  clientName: string;
  clientGstin?: string;
  serviceCategory: AdhocServiceCategory;
  title: string;
  description: string;
  status: 'Pending' | 'In Progress' | 'Review' | 'Completed' | 'Delivered';
  priority: 'High' | 'Medium' | 'Low';
  assignedStaffName?: string;
  assignedStaffId?: string;
  feeQuote?: number;
  targetDeadline?: string;
  completedDate?: string;
  deliverableFile?: string;
  createdAt: string;
  notes?: string;
}

export interface ComplianceCalendarItem {
  id: string;
  dueDate: string; // e.g., "5 Oct", "2026-10-05"
  displayDate: string; // e.g. "5 Oct"
  eventTitle: string; // e.g., "GSTR-1 filing"
  category: 'GST' | 'TDS' | 'Income Tax' | 'ROC' | 'Audit';
  applicableTo: string;
  status: 'Upcoming' | 'Urgent' | 'Action Required' | 'Completed';
  description?: string;
  penaltyInfo?: string;
  isAutoGenerated: boolean;
  affectedClientsCount?: number;
}

export interface PendingTaxItem {
  id: string;
  clientId: string;
  clientName: string;
  clientGstin: string;
  taxType: 'GSTR-1' | 'TDS Deposit' | 'GSTR-7' | 'Advance Tax' | 'GSTR-3B' | 'TDS Return Q2' | 'Tax Audit';
  dueDate: string;
  daysRemaining: number;
  estimatedTaxAmount: number;
  status: 'Pending Files' | 'Under Computation' | 'Ready for Payment' | 'Filed / Challan Generated';
  registeredPhone: string;
  assignedStaff: string;
  lastReminderSent?: string;
}

export interface PendingTaskItem {
  id: string;
  sourceSection: 'statutory_tax' | 'gst_intake' | 'client_approval' | 'staff_review' | 'billing' | 'adhoc';
  sourceSectionName: string;
  clientId?: string;
  clientName: string;
  clientGstin?: string;
  taskTitle: string;
  taskDescription: string;
  dueDate: string;
  daysRemaining: number;
  urgency: 'critical' | 'urgent' | 'upcoming';
  estimatedAmount?: number;
  amountLabel?: string;
  status: string;
  registeredPhone?: string;
  assignedStaff?: string;
  lastReminderSent?: string;
  actionType: 'whatsapp_client' | 'notify_ca' | 'view_section' | 'open_portal';
  targetTab?: string;
}

export interface BillingInvoiceItem {
  id: string;
  invoiceNumber: string;
  clientId: string;
  clientName: string;
  serviceDescription: string;
  serviceCategory: 'Routine GST Filing' | 'Adhoc Service' | 'Tax Audit' | 'ROC Filing' | 'Annual Retainer';
  period?: string;
  professionalFee: number;
  gstAmount: number;
  totalPayable: number;
  invoiceDate: string;
  dueDate: string;
  status: 'Paid' | 'Pending' | 'Overdue';
  paymentMode?: string;
  receiptNumber?: string;
}

export interface MonthlyRequest {
  id: string;
  clientId: string;
  reportingMonth: string;
  year: number;
  monthNumber: number;
  status: MonthlyRequestStatus;
  secureUploadToken: string;
  tokenExpiresAt: string;
  requestedAt: string;
  reminderCount: number;
  lastReminderAt?: string;
  nextReminderAt?: string;
  remindersPaused: boolean;
  noTransactionsDeclared?: boolean;
  declarationNotes?: string;
  declaredAt?: string;
  declaredBy?: string;
  caReviewedDeclaration?: boolean;
  totalFilesReceived: number;
  totalInvoicesExtracted: number;
  unresolvedExceptionsCount: number;
  activeWorkbookVersion: number;
  categoryDeclarations?: Record<string, { status: 'nil' | 'uploaded' | 'pending'; notes?: string; declaredAt?: string; declaredBy?: string }>;
  clientName?: string;
  clientGstin?: string;
  contactPerson?: string;
  registeredPhone?: string;
  assignedStaffName?: string;
}

export interface ChecklistCategoryItem {
  id: string;
  label: string;
  description: string;
  required: boolean;
  status: 'uploaded' | 'missing' | 'nil_declared';
  uploadedCount: number;
  uploadedFiles: string[];
  missingReason?: string;
  nilNotes?: string;
}

export interface DocumentFile {
  id: string;
  monthlyRequestId: string;
  clientId: string;
  gstin: string;
  reportingPeriod: string;
  originalFilename: string;
  storagePath: string;
  fileHash: string;
  mimeType: string;
  sizeBytes: number;
  receivedTime: string;
  source: 'client_portal' | 'staff_upload' | 'whatsapp_webhook';
  uploaderName: string;
  status: 'received' | 'processing' | 'processed' | 'error' | 'duplicate_flagged' | 'password_protected';
  isDuplicate: boolean;
  duplicateOfId?: string;
  scanMethod?: string;
  isPasswordProtected?: boolean;
  scanNotes?: string;
  fileData?: string;
  driveFileId?: string;
  driveWebViewLink?: string;
}

export interface ExtractedDocument {
  id: string;
  documentFileId: string;
  monthlyRequestId: string;
  clientId: string;
  gstin: string;
  pageStart?: number;
  pageEnd?: number;
  docType: 'sales_invoice' | 'purchase_invoice' | 'bank_statement' | 'debit_note' | 'credit_note' | 'other_uncertain';
  docNumber?: string;
  docDate?: string;
  supplierName?: string;
  supplierGstin?: string;
  supplierAddress?: string;
  buyerName?: string;
  buyerGstin?: string;
  buyerAddress?: string;
  placeOfSupply?: string;
  originalInvoiceRef?: string;
  reverseCharge?: boolean;
  currency?: string;
  taxableAmount: string | number;
  cgstAmount: string | number;
  sgstAmount: string | number;
  igstAmount: string | number;
  cessAmount: string | number;
  roundOff?: string | number;
  totalAmount: string | number;
  rawText?: string;
  extractionConfidence?: string | number;
  reviewStatus: 'auto_extracted' | 'verified' | 'flagged' | 'rejected';
  reviewerNotes?: string;
}

export interface ExtractedLineItem {
  id: string;
  documentUnitId: string;
  itemDescription: string;
  hsnSac?: string;
  quantity?: string | number;
  unit?: string;
  rate?: string | number;
  discount?: string | number;
  taxableValue: string | number;
  taxRatePercent?: string | number;
  cgstAmount?: string | number;
  sgstAmount?: string | number;
  igstAmount?: string | number;
  cessAmount?: string | number;
  totalAmount: string | number;
}

export interface BankTransaction {
  id: string;
  documentUnitId: string;
  monthlyRequestId: string;
  bankName: string;
  accountNumber: string;
  transactionDate: string;
  valueDate?: string;
  narration: string;
  referenceNumber?: string;
  debitAmount: string | number;
  creditAmount: string | number;
  balance?: string | number;
}

export interface ValidationException {
  id: string;
  monthlyRequestId: string;
  documentFileId?: string;
  documentUnitId?: string;
  severity: 'critical' | 'warning' | 'info';
  checkType: string;
  message: string;
  details?: Record<string, any>;
  resolved: boolean;
  resolvedBy?: string;
  resolutionNotes?: string;
  createdAt: string;
}

export interface GeneratedWorkbook {
  id: string;
  monthlyRequestId: string;
  clientId: string;
  gstin: string;
  reportingPeriod: string;
  version: number;
  filename: string;
  filePath: string;
  status: 'draft' | 'awaiting_client_confirmation' | 'client_confirmed' | 'corrections_requested' | 'ca_approved';
  generatedAt: string;
  generatedBy: string;
  clientConfirmationText?: string;
  clientConfirmedAt?: string;
  clientConfirmedBy?: string;
  clientCorrectionComments?: string;
  caApprovedAt?: string;
  caApprovedBy?: string;
  caApprovalNotes?: string;
  caOverrideReason?: string;
}

export interface AuditNotification {
  id: string;
  monthlyRequestId?: string;
  clientId?: string;
  clientBusinessName?: string;
  clientGstin?: string;
  eventType: string;
  channel: string;
  recipient?: string;
  messageBody?: string;
  status: 'prepared' | 'sent' | 'failed' | 'simulated_dev';
  details?: Record<string, any>;
  createdAt: string;
}

export interface AuthUser {
  id: string;
  email: string;
  displayName: string;
  role: UserRole;
  phone?: string;
  token?: string;
  assignedClientIds?: string[];
  lastLogin?: string;
}

export type GovtReturnType = 'GSTR-1' | 'GSTR-3B' | 'ITR-1' | 'ITR-4';

export type GovtFilingStatus =
  | 'Draft'
  | 'Validated'
  | 'JSON Generated'
  | 'Uploaded to Portal'
  | 'Filed with EVC/DSC';

export interface GovtValidationCheck {
  code: string;
  title: string;
  status: 'passed' | 'warning' | 'failed';
  message: string;
  details?: string;
}

export interface GovtValidationResult {
  isValid: boolean;
  score: number;
  checks: GovtValidationCheck[];
  summary: {
    passedCount: number;
    warningCount: number;
    failedCount: number;
  };
}

export interface GovtFilingRecord {
  id: string;
  clientId: string;
  clientName: string;
  identifier: string; // GSTIN or PAN
  returnType: GovtReturnType;
  financialYear: string; // e.g. "2025-26"
  returnPeriod: string; // e.g. "082026", "August 2026", "AY 2025-26"
  status: GovtFilingStatus;
  arnNumber?: string; // Application Reference Number or Ack No
  filingDate?: string;
  filedBy?: string;
  totalTaxableValue?: number;
  totalTaxLiability?: number;
  totalItcClaimed?: number;
  jsonFileName?: string;
  jsonPayload?: any;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

